### ISSUE TITLE
Integration with Korean orthography-to-transcription tool

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#160]
See:

Jeffrey J Holliday & Rory Turnbull. (2014). An implementation of Korean grapheme-to- phoneme conversion in R, poster presented at Mid-Phon 19, Madison, WI.

**Comment by stannam** [comment]
cf., https://github.com/stannam/KPNN/blob/master/kPNNpy/hanutil.py
