### ISSUE TITLE
Functional load -- add "average" functional load option

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#198]
Allow users to calculate "relative contrastiveness" in the guise of the average functional load of all pairs in the inventory that include sound X.  cf. Hume et al. (2012)

**Comment by kchall** [comment]
Reopening because I don't think this is in the GUI yet. @mmcauliffe

**Comment by mmcauliffe** [comment]
I'm still not wholly clear on where the best place for this would be.  Would it be another window separate from the current functional load, would it be a optional replacement for the current pair selection widget?

**Comment by bhallen** [comment]
Since this is still functional load, I was planning on trying to have some option that replaces the pair selection widget with a segment selection widget. I'm not even sure if that's possible, though...

**Comment by kchall** [comment]
I was envisioning something like a button "Add individual sounds" (above "add pair of sounds" and "add pair of features") -- then the select box would simply add single segments. (e.g., could populate only the "segment 1" column).

**Comment by mmcauliffe** [comment]
Yeah, that seems doable, let me see what I can whip up here real quick.

**Comment by mmcauliffe** [comment]
It's on develop!

**Comment by mdfry** [comment]
What a rockstar Mr. M

**Comment by kchall** [comment]
^ Seriously! 

I think this looks good! Only potential issue: I tried doing the average functional load *and* exporting a list of all the minimal pairs, and got a blank list....

**Comment by mmcauliffe** [comment]
Ok, I implemented an ugly fix for that, but it really needs to be generalized at some point with the other functions that output something halfway through.  Ideally, they'd all be logging this information anyway, and then we'd redirect it to a user-specified file if they requested it.
