### ISSUE TITLE
ProD for sets of segments

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#316]
Allow ProD to be calculated over a set of segments (like the functional load option -- "each pair separately" vs. "all pairs together"). Currently, we support only "each pair separately" for ProD. To allow "all pairs together":

1. Have user list all segment pairs and environments as normal.
2. Count the frequency of each the segments in the "segment 1" column in environment 1. Sum them. Use that as the frequency of "segment 1" in this environment.
3. Repeat step 2 for segment 2.
4. Calculate the entropy in that environment.
5. Repeat steps 2-4 for all other environments.
6. Calculate overall entropy by weighting the environment entropies by frequency of occurrence of each environment (as normal).

**Comment by kchall** [comment]
Presumably subsumed by #357

**Comment by kchall** [comment]
Currently, #357 does not answer this after all. We still need an "all segment pairs together" option.

**Comment by kchall** [comment]
@jsmackie

**Comment by mmcauliffe** [comment]
As for #321, sets of segments based on differences in +/- in one feature are implemented now. See e638cbd for more details
