### ISSUE TITLE
N/A support

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#320]
Allow people to have N/A values (e.g. in frequency columns) and just be ignored...

**Comment by bhallen** [comment]
Reviving this issue based on #366 

Details: we let people calculate, say, functional load while including the 0 frequency words but excluding the NA frequency words

**Comment by bhallen** [comment]
Add a check in __iter__ in ContextManagers to make sure to ignore anything with NA frequency or 0 frequency iff we're using token frequency.

**Comment by mmcauliffe** [comment]
Should be fixed now
