### ISSUE TITLE
Dealing with pronunciation variants in analyses

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#322]
1. allow user to specify default
2. use the most frequently occurring transcription
3. weight by token frequency
4. allow each variant to count as a separate type

**Comment by mmcauliffe** [comment]
So I have this kind of working for prod and functional load, but I'm not quite sure how to write some tests for it, and what would count as the expected output. I'll work on building a running text based off of our example corpus next I think, since I think a corpus with variants that are all the standard form should be the same as calculating over the CSV style example corpus. After that, I guess I'll play around with making one that has actual variants in it.

**Comment by mmcauliffe** [comment]
I wrote some tests for Prod and FL for pronunciation variants, though they only cover the (not very likely) case of all word tokens having the same pronunciation.  In this particular case, 'most_frequent_type' equals 'relative_type' equals 'type' for non-wordtoken analyses, and likewise 'most_frequent_token' equals 'count_token' equals 'token' for non-wordtoken analyses.

**Comment by kchall** [comment]
So, I finally finished doing a set of ProD tests on the made-up pronunciation variants spontaneous speech corpus (pronunc_variants_corpus.wav / pronunc_Variants_sample.corpus in the tests folder on Dropbox). The results are in s_sh_ProD_results.txt and p_t_ProD_results.txt. I tried running the same tests with all the different possible configurations of type / token frequency in PCT, and just got values of 0 for everything, which obviously isn't correct, so it's hard for me to figure out if PCT is performing as expected! 

(Note that in doing these calculations, I just created variant "versions" of the corpus that used different representations -- e.g., a "canonical_corpus" that uses the canonical transcriptions even when there are multiple variants, etc. -- and these are labeled in the results file. One question: in the event of a tie in the case where the most frequent variant is supposed to be selected, what does PCT do? In my R version, I defaulted back to canonical, but we probably want another option available in the case where canonical transcriptions aren't part of the corpus.)

**Comment by kchall** [comment]
OK, after re-creating the TextGrids with a "segment" tier, PCT will calculate ProD values as expected. The PCT results for [p] vs. [t] and for [s] vs. [sh] all match the hand-done results. 

Some remaining issues:

1. In the event of a tie in the case where the most frequent variant is supposed to be selected, what does PCT do? In my R version, I defaulted back to canonical, but we probably want another option available in the case where canonical transcriptions aren't part of the corpus.

2. The names for the possible analysis options aren't particularly intuitive. In particular, introducing a new distinction between "word types" and "word tokens" in addition to "type frequency" and "token frequency" seems confusing. I would recommend the following:

An option for selecting type vs. token frequency.
a. type frequency
b. token frequency

An option for selecting what to do with pronunciation variants, with the following four choices:
a. Use canonical forms only
b. Use most frequent forms only
c. Count each word token as a separate entry
d. Weight each word type by the relative frequency of its variants

The way these would map on to the current options are (and yes, I know some combinations end up with the same calculations):

New labels: type frequency, canonical forms
Old labels: word types / type frequency

New labels: token frequency, canonical forms
Old labels: word types / token frequency

New labels: type frequency, most frequent forms
Old labels: word tokens / most frequent as type

New labels: token frequency, most frequent forms
Old labels: word tokens / most frequent as token

New labels: type frequency, count each word token separately
Old labels: word tokens / raw counts of each pronunciation (token frequency)

New labels: token frequency, count each word token separately
Old labels: word tokens / raw counts of each pronunciation (token frequency)

New labels: type frequency, weighted word types
Old labels: word tokens / relative counts (type frequency)

New labels: token frequency, weighted word types
Old labels: word tokens / raw counts of each pronunciation (token frequency)

**Comment by mdfry** [comment]
Context Managers completed, now to incorporate them to the GUI and commandline

**Comment by mmcauliffe** [comment]
I just merged in the contextmanagers branch, and all the tests are passing and GUI is functional with all analysis types.

I didn't implement it with phonological search, which we mentioned briefly at the meeting, because I think a simpler solution of searching pronunciation variants vs canonical forms would be better for it.  I don't think it'll make it in for 1.1, but we should revisit it in the future.
