### ISSUE TITLE
Tone!

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#326]
Deal with it.

**Comment by mmcauliffe** [comment]
@kchall how is tone represented in dictionaries?  In the Cantonese corpus, it's the melody given at the end (fam12), correct?  What about multisyllabic words or languages where tone is associated with the vowel instead of the syllable?  Is it like fa1mi2 or fami12?

**Comment by kchall** [comment]
@mmcauliffe It is usually marked after each syllable, so fa1mi2. Blake changed it in the Cantonese corpus we're using so that all tones are given at the end of the word.

**Comment by bhallen** [comment]
Just a note here to clarify that the standard format actually has the tone after the /syllable/, and I modified such a corpus to put tones after their vowels. But, as we discussed today, these systems demarcate syllables using the tone markings, so associations between segments and tones are always unambiguous.

**Comment by mmcauliffe** [comment]
Tone is as much done as stress is now, which is to say it gets parsed into something meaningful, but no analyses or functions take advantage of it.  Something for 1.2, at any rate.
