### ISSUE TITLE
Output minimal pair list

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#333]
Can we add an option to output the list of minimal pairs that is found while calculating functional load?

**Comment by kchall** [comment]
Do something kind of similar for the ProD -- list the words that had each environment. Maybe make a "summary" and "details" results box for many of the algorithms?

**Comment by bhallen** [comment]
@mmcauliffe 

From the GUI standpoint, would we be better off a) modifying these functions to return just the list of words, b) modifying them to return a tuple of the list of words and their length, or c) adding a new parameter that determines whether they return the list or the value? I don't have any particular preference.

**Comment by mmcauliffe** [comment]
I would say the length and the list would be best, since that would be like the way neighborhood density functions currently, and it's probably best to keep the outputs from functions as similar to each other as possible?

**Comment by bhallen** [comment]
@mmcauliffe  @kchall 

This feature is added for funcload, now needs to be added to GUI.

For ProD, the main function appears to already be returning this information, so I think that to do what you've requested, changes only need to be made in the GUI.

**Comment by kchall** [comment]
This is another GUI function that would be useful to have for writing up the manual.

**Comment by mmcauliffe** [comment]
Functional load is done.  I'd say make a different issue for ProD for a future release, since we'd have to change the internals to have it return/save words.
