### ISSUE TITLE
Hayes feature file

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#347]
Apparently [m] is currently specified as [+delayed release]. There may be other errors, too...

**Comment by mmcauliffe** [comment]
I forget where exactly we got these from, but we should probably double check the original and if it's there, let Bruce know about it, too.  Any [m]-like segment is going to be like that across all the transcription styles, correct?  Should we do a more thorough look over it before uploading new files?

**Comment by kchall** [comment]
Yup, Avery's checking the Hayes features for Gitksan (which is how we found this error), and we'll check the others, too....

**Comment by mmcauliffe** [comment]
This seems to be fixed in a version downloaded today, so I'm gonna close it.
