### ISSUE TITLE
Generate subset corpus?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#350]
Getting the following error when trying to create a subset of the Gitksan corpus that is Gitksan and not English:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 188, in accept
    corpus_name_to_path(self.settings['storage'],new_corpus.name))
AttributeError: 'SubsetCorpusDialog' object has no attribute 'settings'

**Comment by mmcauliffe** [comment]
Should be fixed!
