### ISSUE TITLE
Improve long-distance search function

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#359]
(Suggestion from UVic): Allow users to at least include "unlimited amount of unspecified material" between the target and the environment in a search. E.g., "look for [i] followed by [s] anywhere in the word" (rather than strict adjacency on tiers).

**Comment by kchall** [comment]
this is one that I think phonologists will definitely want

**Comment by mmcauliffe** [comment]
So the super basic yes-no long distance search is there as a checkbox in the phono search dialog (on the improve-search branch).

Probably a better way of doing it would be to build it into the Environment creation somehow?  I feel like that would make that dialog pretty clunky though, but maybe there's an elegant way of doing it.

Environments that allow for intervening segments now show up in the table as "_*a" rather than "_a" to differentiate them.

**Comment by kchall** [comment]
Cool! I like the simple checkbox for "Allow intervening segments." But, maybe it does make sense to have it split into two checkboxes, in the environment selection window, one for left- and one for right-hand environments? Currently, if you allow intervening segments, it automatically allows it on both sides, but you might want to search e.g. for actual word-initial [t]s followed anywhere by [i] (or whatever), such that you wouldn't want to allow intervening segments on the left, but you would on the right. I don't think that would make it too terribly clunky...

**Comment by mmcauliffe** [comment]
Yeah, that'd probably be a good idea!  I was thinking that Environments would specify the type of intervening segments that would be allowed in that screen, which would make it super clunky.

**Comment by kchall** [comment]
Oh...yikes. That seems like it would be clunky indeed, though you're right, I can imagine cases in which that would be helpful. Maybe it could be a separate window? e.g., the option on the current environment window would read "Allow for intervening segments" and then there would also be a button labeled "select" (or something) that would bring up a window in which you could pick (in the usual way) segments / featural combinations to allow to intervene?

**Comment by jsmackie** [comment]
This actually almost works. You can specify intervening segments easily. The harder part is having any "any segment" option. Currently, you'd need to click on every segments in the inventory to get that effect, but I don't think it would be too hard to make this easier.

**Comment by jsmackie** [comment]
That commit has a crucial spelling error in the first sentence, and it should say "it is NOW possible", instead of "it is NOT possible"
