### ISSUE TITLE
check offline use of help docs

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#365]
in executable version

**Comment by kchall** [comment]
Unfortunately, no, this doesn't seem to be working. Just downloaded 1.0.1, then tried to open help while being offline, and just get a blank page where the help should be. Going online then allows it to load properly.

**Comment by mmcauliffe** [comment]
Hmm, whoops!  Well then, I'll see if I can track that down!

**Comment by kchall** [comment]
Can download .pdf from ReadTheDocs.
