### ISSUE TITLE
loading corpus without numeric frequency values

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#366]
-you can't sort by the column and get the following error:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/models.py", line 87, in sort
    key=lambda x: getattr(self.corpus[x],self.columns[col].name))
TypeError: unorderable types: str() < float()
Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/models.py", line 87, in sort
    key=lambda x: getattr(self.corpus[x],self.columns[col].name))
TypeError: unorderable types: str() < float()

see also #320

**Comment by bhallen** [comment]
@kchall
develop branch now has a fix for this (and for #320, partly), but I'd like to ask a couple of things.

First, could you try loading your corpus without numeric frequency values now and see if it works? Second, is this just a corpus where some entries have no frequency (equivalent to NA), or a corpus that simply has no frequency column? If it's the latter, and you're still getting this bug, then this issue needs further attention.

**Comment by kchall** [comment]
@bhallen 

Yikes, this was a really unclear issue. There are two situations I know of, one of which seems to be fixed and the other of which is not.

First: there was a corpus with simply no frequency column at all. PCT now reads in the corpus and adds a frequency column with "0" for each word. So, this one is basically fixed. That said, would it make more sense to set the default to NA?

Second, this issue was actually intended to be about corpora that HAVE a frequency column, with entries for all elements, but where the entries are not treated as numeric. E.g., the corpus has numbers with commas in them such that the entire number is treated as a character string. PCT does read these in, and currently seems to be converting the commas to periods, but still isn't reading them properly. You can tell because sorting in the frequency column does not make the entries line up numerically.

**Comment by kchall** [comment]
-set default frequency value to NA if no frequency is given
-remove string values before doing calculations on numeric frequencies

**Comment by bhallen** [comment]
The original problem is now fixed: PCT can read in frequencies that include commas.

I'm not sure how to proceed with the suggestions in @kchall 's last comment, though. If we actually read in all missing frequencies as 'NA', then that'll cause issues with our analysis functions until we can update them. One solution would be to keep the missing frequencies as 0.0, but find some way for the GUI to display them as 'NA' ( @mmcauliffe , is this possible?). Meanwhile, to address the second suggestion, we could start updating the analysis functions to make them ignore any words with a frequency of 0.0. How does that sound?

**Comment by kchall** [comment]
I don't think we should be removing words from the analysis just because they have a token frequency of 0! In the functional load analysis, we allow the user to specify the minimum token frequency already. But for other analyses, I can definitely imagine wanting to run the analysis on type frequency, i.e., all the words in the corpus, even if they have a token frequency of 0. I would rather wait until we can actually read them in as NAs and then update the analysis functions accordingly.

**Comment by bhallen** [comment]
That's a good point... I guess we can't conflate 0 frequency and NA frequency so easily. Your suggestion is to let people calculate, say, functional load while including the 0 frequency words but excluding the NA frequency words, right? Otherwise, what did you mean by "remove string values before doing calculations on numeric frequencies"?

In any case, we should probably create a new issue for this, since the bug associated with this issue is now fixed.

**Comment by bhallen** [comment]
Closing this and moving discussion to #320
