### ISSUE TITLE
Loading corpus from running text in pronunc. variants branch

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#374]
On the pronunciation variants branch: when creating a corpus from running text (Gitksan, Fox in Sox, etc.), the corpus is processed and shows up on the list of corpora. But then I can't actually load it -- it just gives me the progress bar, with no error message, and no corpus. 

I can load the corpora ok on the develop branch. So, maybe it's just that its not even supposed to work on the variants branch...but just in case it is supposed to (or will crash when it's merged in), I thought I'd report it....

**Comment by mmcauliffe** [comment]
Should be fixed now!
