### ISSUE TITLE
Create new example corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#382]
-onset and coda clusters
-complementary distribution for both pairs of segments and pairs of feature-bundles
-vowel harmony
-consonant harmony
-homophones
-non-homophonous homographs
-pronunciation variants
-running text / speech
-more complex neighbourhoods
-more minimal pairs
-alternations

-keep track of all created properties

**Comment by kchall** [comment]
Corpus is done -- just needs to be added so that users can download it.

**Comment by mmcauliffe** [comment]
Added to the download box!
