### ISSUE TITLE
create list of restrictions in example corpus (for manual)

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#383]
Is this all?

- alternations between high and mid vowels: mid only right before a nasal
- consonant harmony: no [s]...[S] without an intervening nasal
- vowel harmony (details: ??)

**Comment by bhallen** [comment]
Question for @mmcauliffe 

I added a new section to the manual, as well as what I think were all the appropriate bits of code to get it to show up in the index. It's in the develop branch, though, and so I don't think it's allowed to show up in even the 'latest' version of our readthedocs site.

Is there any way to check how the docs in develop would render, or do I have to put it into the docs directory in master?

**Comment by mmcauliffe** [comment]
Ah, thanks for the heads up, I'd forgotten to update the repository url for readthedocs, so they should update themselves now, is my understanding.  I added develop to the list of what it should build, so hopefully any commits to develop will trigger a doc build, but I'll keep my eye on it.

**Comment by mmcauliffe** [comment]
Ok, it looks like everything on read the docs is working, it took a while for the develop version to actually be accessible, but it now is.  You can change the version you're viewing down in the lower left hand corner where it says "v:latest".

**Comment by bhallen** [comment]
Great, thanks Michael!
