### ISSUE TITLE
additional feature files

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#385]
@mmcauliffe -- add other choices such as Buckeye feature file when people are downloading features

@kchall -- look into TIMIT feature file?

**Comment by mmcauliffe** [comment]
Is there a buckeye SPE feature file?  I'm assuming not, but then it's the only one that breaks the pattern :(

**Comment by kchall** [comment]
There's now a buckeye2spe.txt file in the "public" Dropbox TRANS folder.

**Comment by mmcauliffe** [comment]
Should all be working now!  I also updated the GUI so that it does error reporting like the rest of the GUI if something goes wrong while loading from CSV.
