### ISSUE TITLE
Load from pre-formatted text file, Develop Branch

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#387]
1. When correcting a file name and using the delete key, I got the following error (which didn't seem to crash PCT, but which I was instructed to report to the developers):

2. When loading in the CELEX epw file (formatted for PCT), the column names and settings, etc., appear correct. But clicking on "Recheck file using current settings" returns the following error:
"The column delimiter specified did not create multiple columns." (the automatically detected, and correct, column delimiter is \t)

3. When I try to load the corpus anyway, I get the following error: "Could not parse transcriptions with that delimiter. 
\Check that the transcription delimiter you typed in matches the one used in the file." (the automatically detected, and correct, transcription delimiter is nothing -- i.e., this is a one-character-per-sound corpus)

**Comment by mmcauliffe** [comment]
The first issue should be all fixed, I can't replicate the second one with the example corpus though, do you think you could put the celex file up on dropbox?

**Comment by kchall** [comment]
Here's a link to it: https://www.dropbox.com/s/zpo7ej6k4qs8lo3/celex_epw_for_PCT.txt?dl=0

**Comment by mmcauliffe** [comment]
Should be all fixed now.  The issue was that while the transcription column wasn't being detected as a tier type of column (since there was no delimiter to detect), so I fixed it so that if the column is named transcription, it'll be detected as a tier.  I'll add some functionality to the special column selection (so that frequency can only be a numeric, transcription only a tier, and spelling only spelling).

**Comment by kchall** [comment]
Yup, that seems to work -- i.e., I was able to create the corpus. It is actually still the case that clicking "Recheck file using current settings" still gives me the same error as above, though it doesn't seem to have actual consequences...

**Comment by mmcauliffe** [comment]
Ok, fixed that, it shouldn't give any more errors now.

**Comment by kchall** [comment]
Yup, all seems good to me!
