### ISSUE TITLE
Lack of features in Gitksan corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#400]
In one Gitksan corpus (Barbara_stories_April_9_orthnomorph_nocaps.corpus in the test files Dropbox folder), the feature files seem to be correct and allow PCT to organize the segments into IPA charts, but when a phonological search is conducted, there are no features listed in the "basis for search" section, and features aren't even a choice in the "environment" section. This seems to be a problem with this particular corpus, as the feature file works fine with other corpora, and all other feature files run in to the same problem with this corpus.

**Comment by kchall** [comment]
Further investigation shows that this is a recurrent problem with trying to associate a feature file with a corpus that has been created from running text. I was able to "fix" the problem in another instance by exporting the created corpus as a tab-delimited .txt file and re-create it from that new .txt file, and then associating the feature system to it. So it seems to be a real issue, and somehow connected to corpora that are created from running text. @mmcauliffe

**Comment by bhallen** [comment]
@kchall 
I'd like to fix this bug, but first I need to be able to replicate it. Could you please send me the Gitksan running text file so that I can do this? I don't have access to the general-purpose Dropbox folder anymore.

**Comment by mmcauliffe** [comment]
Sorry, I probably should have closed this a while ago.  I'm almost 100% positive that I fixed on the develop branch when looking at the lack of features for Avery and Michael's project.  I'm guessing that the recent update from @kchall  was on the io-standardize branch?

**Comment by kchall** [comment]
Hmm, I was looking at it in v. 1.0.1.

It does seem to be working ok now on the develop branch. Sorry for the confusion!
