### ISSUE TITLE
Bug in loading formatted corpus?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#405]
On the develop branch, trying to load in a new, formatted corpus (Lexique):

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/main.py", line 181, in do_check
    function(self)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/main.py", line 271, in loadCorpus
    self.corpusModel = CorpusModel(c, self.settings)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/models.py", line 311, in __init__
    self.rows = self.corpus.words
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1379, in words
    return sorted(list(self.wordlist.keys()))
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 397, in __gt__
    return self._list > other
TypeError: unorderable types: list() > str()

**Comment by kchall** [comment]
(seems to be because it's making the Spelling column a Tier by default)

**Comment by mmcauliffe** [comment]
Is this still an issue with the new IO gui?

**Comment by kchall** [comment]
Nope, it seems to be fixed. But somewhat relatedly: it's still the case that the default interpretations of columns are a bit odd. "spelling" gets interpreted as orthography, which is good, and "frequency" as other (numeric), which is good; but all other columns, including "transcription" and columns with other labels such as "syllables" or "freqlivres" or whatever all got considered to be "orthography" columns named "spelling." "Transcription" definitely needs to default to "transcription," and the others should probably default to other (character).

**Comment by mmcauliffe** [comment]
Does the transcription column not have a segment delimiter in it?  It's changed to default to other (character), but if the transcriptions aren't delimited, there's no real way to detect transcription columns from spelling columns.

**Comment by kchall** [comment]
Thanks. No, this transcription column uses a period as a delimiter (which for some reason was not detected for some reason). But in general, would it be possible to make any column whose original name is "transcription" or "Transcription" to be read in as a transcription column, regardless?

**Comment by kchall** [comment]
Solution: default to numeric or character.
