### ISSUE TITLE
Check for math domain error in ProD

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#410]
/l/ plus all vowels in IPHOD in ProD --> returns math domain error?

**Comment by kchall** [comment]
Hmm: "To get the math domain error, I basically highlighted all possible vowels and consonants in the segment section of the pairwise comparison and asked it to compute the predictability of distribution.  I think I probably just asked it to do too much!"

I agree. :) But perhaps we should double-check the error reporting on it?

**Comment by bhallen** [comment]
@kchall  @mmcauliffe 
I'm not able to replicate this math domain error. I've tried adding all segment pairs and calculating ProD, both with and without environments specified, but it works fine. Has this bug been fixed but its issue not closed?

**Comment by kchall** [comment]
I never got the error myself -- it was also from a user, and all I know is listed above.
