### ISSUE TITLE
feature selection comments

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#411]
I like the basic idea of the new feature-selection method (i.e., typing things in and having auto-complete). A couple of comments:

-Intuitively, I wanted to put commas between the features, and that doesn't work. Maybe that's ok, as long as we're explicit that it has to be spaces. (And *no* commas too. I think I got confused because if you do a comma after the first one, plus a space, then it seems to be working, but subsequent features aren't registered.)

-I'm still having trouble figuring out how the delete / backspace works. Sometimes, I can delete single characters, but sometimes it deletes everything I've typed. This is annoying when I've just actually made a typo on the third feature... (It seems as though if you've typed a space after a feature name, it then lets you backspace by character, but if you're in the middle of the feature, it deletes everything to the previous space? Unless you do have a comma, in which case it deletes everything, even if there was a space, too....)

-If you mis-type something, it sometimes deletes all the feature selections (rather than just saying "feature selection not recognized"). E.g., if you type -syllabic +cor _voice (instead of -voice), all the features are cleared (but the coronal consonants are still highlighted in grey until "Clear Selections" is selected). 

-Similarly, if you type a feature name that doesn't exist, it sometimes deletes the whole feature name (if you hit return after typing the name), and sometimes just lets you keep going but doesn't select any segments (if you type a space and then keep going).

-Currently, in the develop branch, in windows that don't have the new feature selection option, we're back to seeing the whole inventory all at once (i.e., not checkboxes for vowels and consonants nor a scrolling window), which in turn means that the boxes tend to be larger than my screen and I can't actually run analyses because the "Add to environment" or "Calculate" buttons aren't accessible.

**Comment by mmcauliffe** [comment]
@kchall Just pushed a new commit to develop, could you check out the feature completion stuff again and let me know if you have any issues?  I rolled back the fancier backspace stuff, so it should behave more like a regular text field, and updated the delimiter parsing to accept anything involving a comma, space, or semicolon, which should cover everything that people would enter.  It does standardize the delimiters at times to the first one entered, but that shouldn't be a huge deal.

**Comment by kchall** [comment]
Yes, this seems good! More intuitive and less persnickety. ;-) The only kind of annoying thing at the moment is that if you select sounds by feature, the sounds are just highlighted in the inventory, but NOT actually selected -- you then have to click each one to get them added. Maybe we add a global button for something like "Select all highlighted sounds"? @mmcauliffe

**Comment by mmcauliffe** [comment]
Oh, if you hit enter after typing in a feature specification and the completion dropdown isn't visible, it will select all the highlighted segments! I could add a button that does the same thing, too.

**Comment by kchall** [comment]
Oh, I see. That means, though, that you have to hit "enter" twice if you're selecting an auto-complete feature. Definitely wasn't intuitive to me. ;-) So a button would be useful! Thanks.
