### ISSUE TITLE
Adding environments box

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#420]
(AO): "When choosing environments using segments, having to add them each individually, and in particular not getting to see the ones you've already added, is kind of frustrating. It would be nice if in the environment-adding box, it were possible to either choose a bunch of environments at once (the way you can choose the segments you're looking for) or see which ones you've already chosen there instead of only in the main search box."

**Comment by bhallen** [comment]
It sounds like this is the sort of thing that will be fixed in io-standardize, right? I'm imagining we will have a pane with current environments and then another pane for adding a new one...
