### ISSUE TITLE
"Save as..." option on features / inventories

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#422]
Make sure that changes to a feature inventory can be saved as a new file instead of just over-writing the current one.

**Comment by mmcauliffe** [comment]
I'm going to move this to 1.2, since I don't think it's a high priority.

**Comment by jsmackie** [comment]
I've got this fixed up now. If you make any edits to a feature system, you get a window asking if you want to overwrite your old file, or if you want to save a new one under a new name. There's also a checkbox added which says "don't ask me again - always overwrite feature files". If you want to turn on the reminder later, you can go to Options > Preferences... and there's a new Reminders tab with a checkbox for this.
