### ISSUE TITLE
Functional load -- context managers bug?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#424]
Buckeye corpus
looking at [t]/[d], [th]/[dh], [t]/[th], [d]/[dh]
calculating functional load, on each pair individually
using canonical forms (though I get the same error with other ways of handling pronunc. variants)

"Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/flgui.py", line 44, in run
    res = func(c, [pair], **kwargs)
TypeError: minpair_fl() got an unexpected keyword argument 'frequency_cutoff'"

@mmcauliffe @mdfry

**Comment by mmcauliffe** [comment]
Should be fixed now!

**Comment by kchall** [comment]
It is, thanks!
