### ISSUE TITLE
Pronunciation variants -- add to results table

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#425]
The strategy for dealing with pronunciation variants that was chosen should be included in the results tables for each of the functions that has it as an option.

**Comment by kchall** [comment]
It would probably also be helpful if the name of the corpus was also always listed by default, too....

**Comment by mmcauliffe** [comment]
As part of this, it'd probably be helpful to have a standard format for the table.  Where should all this extra information come?  If the heading is "Segment 1, Segment 2, Result", should it come after the result or before it?  And is there a preference on the order of the extra information?

**Comment by kchall** [comment]
Hmm, maybe:

Corpus
Segment 1
Segment 2
Parameters (Algorithm, Tier, Kind of Frequency, Pronunc Variants Strategy, Others)
Result

(where the "others" will simply vary by analysis function -- e.g., whether homophones are included; what the minimum frequency is; threshold similarity value; etc.)

**Comment by mmcauliffe** [comment]
Ok, so it now goes:

Corpus
Things to be analyzed ("First Segment, Second Segment", "First Word, Second Word", "Word", depending on function)
Algorithm (if applicable)
Algorithm details (if applicable)
Transcription tier (or "String type" if spelling is an option)
Frequency type
Pronunciation variants
Frequency cutoff (if applicable)
Result
