### ISSUE TITLE
Corpus Summary window

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#429]
1. Inventory boxes don't have scroll bars, so they don't fit on the laptop screen.

2. Error message when clicking on an element in a corpus to get its frequency:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/corpusgui.py", line 52, in summarizeSegment
    freq_base = self.corpus.get_frequency_base('transcription', 'type', gramsize = 1,
AttributeError: 'Corpus' object has no attribute 'get_frequency_base'

**Comment by mmcauliffe** [comment]
Should be fixed now!
