### ISSUE TITLE
frequency ties in context managers?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#430]
@mmcauliffe, @mdfry  -- What does PCT do when there is a tie for the most frequent form? pick one? how? weight them equally? Just want to make sure I describe it correctly in the manual...

**Comment by mmcauliffe** [comment]
At the moment it would follow Python's algorithm, which is just to pick one (at more or less random, I assume it's based on the ordering of the hashes, which is not necessarily the alphabetical ordering).  What behavior would you like it to have?

**Comment by kchall** [comment]
It definitely shouldn't be random. I think the best would be some sort of weighted version, but probably the easiest good option is to do (1) most frequent; if there isn't one then (2) canonical; if there isn't one then (3) first alphabetical.
