### ISSUE TITLE
"Add column" function is delayed

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#436]
When a new column is added using "Add column," it doesn't appear unless and until an *additional* column is added (which in turn doesn't show up until another one is added, etc....).

**Comment by mmcauliffe** [comment]
Hmm, weird, it works for me, I'll check on a mac at some point.

**Comment by kchall** [comment]
Hmm, I re-synced and tried again, and it seems to be ok now...
