### ISSUE TITLE
Empty labels in the inventory steal segments in the Feature Matrix tree view

### ISSUE THREAD

**Issue by mmcauliffe** [PhonologicalCorpusTools/CorpusTools#446]
For instance, if trill or tap is not specified (i.e., no features specifying them), the trill or tap label will take all fricatives and everything below.  To fix, make the behavior consistent in ignoring empty feature labels for the tree (as it does in the inventory box).  Noted by AO

**Comment by mmcauliffe** [comment]
Lower priority, moving it to 1.2 rather than 1.1.1.

**Comment by kchall** [comment]
Tree view has been deleted??? @jsmackie

**Comment by kchall** [comment]
I don't think this is relevant anymore, because the whole feature system implementation is completely different from where it was 3 years ago. There is no tree display mode anymore.
