### ISSUE TITLE
Empty diphthong specification for the inventory label results in no inventory table

### ISSUE THREAD

**Issue by mmcauliffe** [PhonologicalCorpusTools/CorpusTools#447]
Work around is to specify a non used feature specification, something like (0back, if no monophthong vowel fits that description).  Noted by AO.

**Comment by bhallen** [comment]
I can't replicate this bug. @kchall @mmcauliffe Do either of you have the relevant corpus file, or at least the feature file? Also, I assume the bug comes in when trying to select segments for e.g. ProD, right?

**Comment by mmcauliffe** [comment]
To replicate it, open up iphod or example, go to view/change feature system, then Edit inventory categories, and then delete the field for Feature specifying diphthongs, and then save changes.  Any inventory box will now just be a list of segments, rather than a table.
