### ISSUE TITLE
Error in loading CSJ from TextGrids with Feature File

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#448]
In 1.1, trying to create the whole CSJ corpus from TextGrids, with a newly added csj2hayes feature file:

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/iogui.py", line 103, in run
    corpus = load_directory_textgrid(**self.kwargs)
  File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 342, in load_directory_textgrid
    feature_matrix = load_binary(feature_system_path)
NameError: name 'load_binary' is not defined

**Comment by kchall** [comment]
It does work to load the corpus without a feature file. But because there are no "official" transcriptions, I can't even view/edit the feature system post-hoc.

**Comment by kchall** [comment]
Had the same problem with the Gitksan running text...can't load it with the feature file, but it is ok to add the feature file afterward.

**Comment by mmcauliffe** [comment]
Should be fixed on master.

**Comment by kchall** [comment]
Yes, looks good.
