### ISSUE TITLE
can't save changes to corpus's feature system

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#455]
I tried to import a corpus from the Gitksan love story running text, and then to import the gitksan2hayes feature file to apply it to the corpus. Loading the feature file works fine. I go to "View/change feature system" to apply the transcription/feature system to the corpus, and I select the appropriate systems and then press "Save changes..." But then the next time I open the "View/change feature system" dialog, the transcription/feature system boxes are blank again. I can't get any segments or features to display here either.

**Comment by mmcauliffe** [comment]
I can't replicate it with the versions of the files that I have.  Could you email me the two files and I'll check it out?

**Comment by kchall** [comment]
This happens to me with my version of the Buckeye corpus, too. But I think it's probably localized to some corpora, because it works fine with others. Blake, can you try on a different corpus?

**Comment by bhallen** [comment]
Hm, I think it may actually be an issue with the feature/transcription file rather than the corpus itself. The Gitksan corpus seems to work fine when I specify IPA as the transcription and provide a compatible feature system. Still no exceptions in the terminal, though.

**Comment by bhallen** [comment]
Kathleen's case: problem may be related to the fact that she changed the .corpus filename in Documents

**Comment by bhallen** [comment]
I just looked into this issue again, and I noticed some behavior that might help us diagnose the problem. After loading a corpus and going to the 'Edit feature system' dialogue, I notice that the inventory table on top only displays if the selected transcription system is compatible with the selected feature system. Moreover, any changes to a corpus's feature system are only changed if the transcription/feature selections are compatible.

So for the Gitksan case in particular, I'm wondering whether I might just have the wrong feature/transcription files, or whether maybe these files are deficient in some way. @kchall could you please email me these files so I can double-check that I'm using the right ones?

More generally, it seems like it'd be a good idea to explicitly warn users if they select a transcription system and a feature system that are incompatible with each other. I think it would also be useful to warn users if their corpus's transcriptions include segments not specified in the current feature/transcription system---maybe when they press the "Save changes" button? Does this seem reasonable or am I missing some reason we didn't include these warnings?

**Comment by jsmackie** [comment]
Which branch is this on? I'm pretty sure that I fixed this in
developInventoryView.

**Comment by bhallen** [comment]
I was on develop. I tried to see if the same thing happens on developInventoryView, but it won't let me load the Gitksan corpus:

Traceback (most recent call last):
  File "/home/blake/repos/CorpusTools/corpustools/gui/main.py", line 197, in do_check
    function(self)
  File "/home/blake/repos/CorpusTools/corpustools/gui/main.py", line 255, in loadCorpus
    if self.corpus.specifier is None:
AttributeError: 'Discourse' object has no attribute 'specifier'

**Comment by bhallen** [comment]
@kchall I just checked with the Buckey corpus you sent me. I can't find any difference in behavior between when I've renamed Speakers.corpus to Buckeye.corpus versus when I've left its name unchanged.

However, with either corpus file name, I'm getting unwanted behavior very similar to what I got with Gitksan. The crux of the issue here seems to be that a feature-transcription combination fails to be saved when it's an incompatible combination. On the Buckeye corpus, for example, if I set Transcription to 'ipa' and Feature system to 'hayes', this is saved just fine. If I set Transcription to 'arpabet' and Feature to 'hayes', it's saved fine. But if I set Transcription to 'ipa' and Feature to 'hayes_nodiph', or if I set Transcription to 'ipa_nodiph' and Feature to 'hayes', the new feature/transcription system fails to be saved. (Note, importantly, that 'ipa_nodiph' with 'hayes_nodiph' works fine!)

Could someone with more knowledge of how feature and transcription systems are handled look into this? Should we at least add a warning when people select an incompatible feature/transcription combination?

Oh and @kchall I had actually intended to ask you for the Gitksan files, so please send that over when you get a chance. :)

**Comment by kchall** [comment]
Oh, I see what you're saying. "Incompatible" combinations should be ones where there simply is no file that links the two together (i.e., there's no "ipa_nodiph2hayes" file). I have no idea why ipa_nodiph2hayes_nodiph would work unless you've actually added a symbol 2 feature mapping file with that name. I agree that adding a warning would be useful.

I was actually having the problem where real existent feature files were not saved. e.g., with the Buckeye corpus I sent, I can associate a real feature system (buckeye2hayes or whatever) to it, save it, use it in PCT for analyses, etc., and then when I close PCT and re-open, it has failed to save the feature system, and I have to start over. This is much more unexpected, because it's not just a non-existent feature / transcription system.

I'll send you some Gitksan files, but I'm not sure which ones you need in order to replicate the above behaviour.

**Comment by jsmackie** [comment]
This issue is pretty old now, and the corpus loading system has since changed, so I think this can be closed.
