### ISSUE TITLE
Missing TextGrid module?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#461]
Not sure exactly what happened...but currently, in both the released version and the develop branch, there's a problem with importing a corpus from a TextGrid. In the released version, everything is fine until you select a .TextGrid file in the system dialogue box -- even before you click ok, the whole thing crashes. On develop, I actually can't open the GUI at all; running the pct_qt_debug.py script results in the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/bin/pct_qt_debug.py", line 5, in <module>
    from corpustools.gui.main import MainWindow,QApplicationMessaging
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 14, in <module>
    from .iogui import (CorpusLoadDialog, SubsetCorpusDialog, ExportCorpusDialog,
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 18, in <module>
    from corpustools.corpus.io.textgrid import (inspect_discourse_textgrid,
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/textgrid.py", line 5, in <module>
    from textgrid import TextGrid, IntervalTier
ImportError: No module named 'textgrid'

The reason this seems particularly odd to me is that immediately prior to this, I had successfully imported a corpus from a TextGrid on the released version. I was going to try re-importing it with different settings when the above crashing happened.

**Comment by mmcauliffe** [comment]
So I just tested it on a newly downloaded released version and it worked fine.  To get the exact error message in the binary version, you can right-click on the PCT app, click "Show package contents" and then navigate to "Contents/MacOS" and then double click on "pct".  That should show a terminal output for anything that goes wrong.  

In terms of fixing it, could you try it again after restarting your computer or something?  Or after redownloading it?  That seems like a super weird bug.  For use on the develop branch version, you can install textgrid via pip now ("pip install textgrid" or "pip-3.4 install textgrid"), though I thought it was installed previously.

**Comment by kchall** [comment]
It's definitely something very odd... I didn't get a chance to re-start yet, but I tried again this afternoon and got as far as setting the import settings and having PCT start to import the corpus before it crashed. Then, trying again, it does the same as above -- i.e., crashes as soon as a .TextGrid file is selected. The terminal output when it does this is:


Last login: Fri Sep 18 11:23:37 on console
dhcp-206-87-223-115:~ KCH$ /Applications/Phonological\ CorpusTools.app/Contents/MacOS/pct ; exit;
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
2015-09-21 14:50:55.475 pct[5140:707] *** WARNING: -[NSImage compositeToPoint:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
2015-09-21 14:50:55.475 pct[5140:707] *** WARNING: -[NSImage compositeToPoint:fromRect:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Segmentation fault: 11
logout

[Process completed]

**Comment by kchall** [comment]
Ok, it worked when I re-installed textgrid.
