### ISSUE TITLE
warn people about deleting an open corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#463]
disallow / warn if someone tries to delete a corpus that is currently open

**Comment by bhallen** [comment]
Do you mean if they try to delete it on their filesystem/hard drive? I'm not sure we can tie PCT into the OS nicely enough to actually warn/stop someone trying to delete a file, but we could add an informative message to the PCT GUI for cases where PCT tries to access a corpus or feature file that is no longer found on the hard drive. Would that address the concern here?

**Comment by bhallen** [comment]
Also, what are the specific cases we've seen so far where PCT actually tries to access a corpus/feature file on the hard drive after it's been initially read into memory via load corpus?

**Comment by kchall** [comment]
This is the point that @jsmackie brought up yesterday. Basically, if you have a corpus open and then go to "Load corpus" and select the same corpus that is open, and choose "Remove corpus" from within PCT, it allows you to do so (deleting it from the Documents folder), but keeps the corpus open in PCT from working memory. You can even still edit things, but then of course you run into problems if you try to save it or re-open it, because the back end has been deleted. 

I think that we should just have it run a check to see whether the corpus is open when someone says "remove corpus" and then not allow them to remove it if it is open.
