### ISSUE TITLE
bug in exhaustivity (ProD)?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#469]
In the example corpus, doing a ProD analysis on feature-defined pairs (i.e., using [high] to define [i, u] vs. [e, o]): if you don't include all the relevant environments, you don't get an exhaustivity error notice. (e.g., if you do __[+nas], __[-nas] and leave out __#, there's no warning -- but [i] occurs word finally). The error correctly shows up if you do the pairs of segments individually rather than defining the sets by feature.

**Comment by bhallen** [comment]
Currently I can't even get the ProD GUI to let me add a featural environment. Kind of similar to our issue #455, I select a feature from the dropdown menu and confirm, but when I look at the environment again there's nothing there. I've tried on develop, master, and developInventoryView. Could someone please try replicating this as a sanity check for me?

By the way @jsmackie on developInventoryView, I notice that there are no # available in the segment selection widget dialogues. Just a heads-up!

**Comment by bhallen** [comment]
@bhallen Try on release 1.1.1 to see if it's possible to replicate the behavior Kathleen reported.

**Comment by devyn** [comment]
Related to #494. Need to catch errors from child threads and report them.

**Comment by kchall** [comment]
@bhallen -- I just tried on the current Develop branch, and exactly the same thing happens. I can select segments based on the feature [high] but don't get an exhaustivity error even when I don't select all relevant environments.

@jsmackie says he fixed some issues related to the selection of segments by feature on his DevelopInventory branch.

**Comment by jsmackie** [comment]
This should be fixed now. However, I discovered another potentially worse bug while doing this. See issue #540
