### ISSUE TITLE
lexical category information in Buckeye corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#478]
Can we give users an option to read in lexical category information in the Buckeye corpus? (and similarly other non-essential info. in other corpora) @mmcauliffe

**Comment by mmcauliffe** [comment]
This should already be possible, when loading the corpus, there should be an annotation type for Category, which defaults to a token property.  If you change it to a type property, then it'll show up in the lexicon.  

With that said, the part of speech tags for the Buckeye corpus are not great, they were done automatically using a tagger trained on written text, I believe, and the accuracy they report for what they checked is about 90%.  For reference, taggers trained on text and tested on text generally tend to have 99% accuracy, so the category tags are not super reliable for the Buckeye.

**Comment by kchall** [comment]
Ah, perfect -- thanks! We were just talking about doing replication studies, and Wedel et al. use the parts of speech (I assume as is) to subset the Buckeye corpus in doing the FL measures.

**Comment by mmcauliffe** [comment]
Maybe, it might be worth double checking that.  I know in other studies using the Buckeye corpus, namely Yao Yao's dissertation and the subsequent Gahl et al 2012 paper, they got category info from CELEX.  Also I've seen some versions that don't have part of speech.

**Comment by kchall** [comment]
Yeah, I asked Andy in Stuttgart where he got the info. from, and he said it was the pre-coded categories in Buckeye. But you're right that if we really do a replication, we should verify!
