### ISSUE TITLE
Functional Load / Delta-H issues

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#487]
1. If I use the new -x argument to get all the pairs calculated separately, I get a new error, but only when using the deltah algorithm (it's fine with minpair):

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pct_funcload", line 9, in <module>
    load_entry_point('corpustools==1.1.0', 'console_scripts', 'pct_funcload')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/corpustools-1.1.0-py3.4.egg/corpustools/command_line/pct_funcload.py", line 112, in main
    outstr += str(element[1]) + '\t' + str(element[0]) + '\t' + '\t'.join([str(getattr(args,a)) for a in vars(args)]) + '\n'
TypeError: 'float' object is not subscriptable

2. If I just do the deltah algorithm on a single pair of segments, to avoid the above problem, I get a really large number, which seems weird. Specifically, if I do the FL of B/D in the IPhOD corpus and restrict it to #_AA environments, the FL using the deltah algorithm is 15.51 bits, which is enormously high. If I don't restrict the environments and just use deltah across all environments, I get a more reasonable-sounding 0.018. I haven't tried it with other pairs yet, but this seems suspicious to me.

**Comment by bhallen** [comment]
@kchall 
My last commit to develop refactored the deltah_fl function. Could you please check to see whether you're still having either of the problems you mentioned in this issue? I've tried to copy what you've described and haven't encountered any errors or strange entropy values.
