### ISSUE TITLE
"About" information

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#493]
Put the old information from the "About" boxes into tooltips that appear when one hovers over the "About" buttons. Take out the "author" information for each function because there is so much overlap. Make sure that the "Help" / "About" menu option is available on Macs and that the information there (http://corpustools.readthedocs.org/en/latest/about.html) is available from the general Read the Docs Table of Contents.

**Comment by jsmackie** [comment]
This issue can potentially be closed now. The tooltips work, and as far as I can tell the links work too. I can't test the Mac/about issue without a mac however.

**Comment by kchall** [comment]
Hmm, I don't see any "About" option either in the "Help" menu within PCT on my Mac, or even in the online ToC.

**Comment by kchall** [comment]
OK, but I did fix it in the online ToC, so that's fine...I'm less worried about having an "About" menu within the "Help" menu on a Mac.
