### ISSUE TITLE
Mac OS 10.11: progress bar appearing when opening analysis dialogs

### ISSUE THREAD

**Issue by devyn** [PhonologicalCorpusTools/CorpusTools#505]
Doesn't seem to happen on OS 10.8, or other operating systems.

Clicking cancel does nothing. No progress is made; nothing appears to be running.

**Comment by mmcauliffe** [comment]
I've had this happen on my Windows 10 laptop, but it also (sometimes) coincides with a warning about size hints.  My current hypothesis is that it's because of my 4k resolution, or it could potentially be a bug in (Py)Qt 5.5.  Closing the dialog (rather than cancelling) should be a workaround.

**Comment by devyn** [comment]
I have a 4K monitor at home. Can test it there.

**Comment by jsmackie** [comment]
@mdfry reported this problem at PCTFest2, and we thought that it could be related to Windows 10. Given the comment by @mmcauliffe above, that seems very likely.

**Comment by kchall** [comment]
Seems to be fixed? (on Roger's Mac)
