### ISSUE TITLE
Uncategorized segments -- show features

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#506]
When a segment is uncategorized, allow double-clicking in the inventory window to show the current specifications of that segment.

**Comment by jsmackie** [comment]
Holding your mouse over an uncategorized segment will now show any partial matches.

**Comment by kchall** [comment]
Ah, this is cool. But it's actually not what I meant. :) This shows where the segment can fit in to current places that are defined in the chart. What I intended was to be able to pull up a list of the total featural specifications for the segment, so that you could see what other features might be useful that HAVEN'T already been used to define chart places.
