### ISSUE TITLE
Inventory fixes

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#508]
-allow someone to force auto-categorization
-make sure default features for vowels and consonants** show up
-show all matches for segments, not just the first match
-provide some way of seeing all the feature specifications for a segment without having to go to the manage feature system window

-create a new corpus from text file (attached) -- try to load it in, get the following error:
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 199, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 287, in loadCorpus
    if self.corpus.specifier is None:
AttributeError: 'Discourse' object has no attribute 'specifier'

[test_text_spelling.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/176619/test_text_spelling.txt)

**Comment by kchall** [comment]
also: if you open a corpus (e.g. the example corpus) for the first time and go straight to the manage inventory chart, get the error message that says to go to the feature chart first

**Comment by jsmackie** [comment]
- Forced autocategorization works (and so does forced removal of all categories)
- Double-clicking uncategorized segments gives a full feature specificiation
- Multiple partial matches work.
- Default consonants features should show up now for newly-created corpora. For older corpora, like the downloadable example corpus, you will have to either enter it manually (once) or else use the autocategorization button.

The other problem with the attached file is actually unrelated to the inventory. It has to do with the way that corpus objects get created from running text. I'm going to close this current issue, and open another instead.
