### ISSUE TITLE
Functional Load results reporting

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#513]
There is a discrepancy between how minimal-pair based functional load results are reported in the results table and how they are reported in an outputted wordlist. In the wordlist, all minimal pairs of WORDS hinging on a contrast are reported (e.g., in asking for minimal pairs with [aw] / [ow], all three of flaw / flow, flaw / floe, and flaw / Flo are presented, so there are three pairs). But in the results table accompanying the same analysis, these three pairs are collapsed into a single pair, presumably based on the transcription [flaw] / [flow], such that the reported result is "1." 

Personally, my default interpretation of asking for the number of minimal pairs that hinge on a contrast would match the wordlist option (i.e., 3 in this case), so if we only report one version, I would vote for that. I can see a case being made for the other interpretation, though, but if we do so, we need to make it crystal clear which option is being selected, and certainly we need to make the two outputs consistent with each other! 

(I am not sure yet whether this also has an impact on the relative counts version of minimal pair FL and / or the change in entropy version.)

**Comment by bhallen** [comment]
Change funcload/io/save_minimal_pairs to list transcriptions as well

And add a tooltip to the FL bo for saving a list of minimal pairs: something like "Note that whether "Distinguish homophones" is checked or not, this file will include all minimal pairs with unique spellings"

**Comment by bhallen** [comment]
Update self.saveFileWidget.setToolTip to have text from pct_funcload

And update docs

**Comment by bhallen** [comment]
resolved by 7407b232570faa3ba9126c682323d85e02cb0657
