### ISSUE TITLE
xcb plugin issue

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#515]
Right now I can't run the develop version's GUI at all: both pct_qt_debug.py and pct (via install.py) give this error...

_This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Aborted_

I've tried a ton of potential solutions around the internet, but as a last ditch effort I thought I'd make an issue here and see whether anyone has some ideas. Maybe @mmcauliffe ? I'm using conda with a Python3 environment, and I've tried reinstalling PyQt5.

**Comment by mmcauliffe** [comment]
Hmm, according to SO, doing `sudo apt-get install libx11-xcb1` might solve it?  Also take a look at http://doc.qt.io/qt-5/linux-requirements.html and see if you're missing any system libraries.  What version Ubuntu/PyQt5 is this?

**Comment by bhallen** [comment]
I already installed libx11-xcb1, and I have all the listed dependencies installed as root. I'm running Linux Mint 17.2, and PyQt5 is version 5.5.1 installed from https://conda.anaconda.org/mmcauliffe/pyqt5 using conda. I even tried installing qt5 from there as well. Do you think I should maybe try a Python3.4 conda env instead of 3.5.1?

**Comment by mmcauliffe** [comment]
Ok, so I'm assuming that Qt5 got installed to a path like "~/miniconda3/envs/{env_name}/Library/lib/qt5/" (subbing in the environment name, of course). And then you should be able (in a terminal) enter: `QT_PLUGIN_PATH=~/miniconda3/envs/{env_name}/Library/lib/qt5/plugins` and then try running it again?

**Comment by bhallen** [comment]
That's a good idea, but unfortunately it didn't work. I've noticed though that even though I have libx11-xcb1 installed, there is no actual libxcb.so anywhere in .../plugins. The only files that match a grep for xcb in .../plugins are .../plugins/platforms/libqxcb.so , .../plugins/xcbglintegrations/libqxcb-egl-integration.so , and .../plugins/xcbglintegrations/libqxcb-glx-integration.so . I'm thinking I should try grabbing libxcb.so from somewhere (or making a symlink) and put it in here somewhere, but I'm not sure where. Where is it in your directory structure?

**Comment by mmcauliffe** [comment]
Ok, so I found a environment variable for mine that is `QT_QPA_PLATFORM_PLUGIN_PATH=~/miniconda3/envs/{env_name}/Library/lib/qt5/plugins/platforms`, so maybe I ran into something similar at some point... Maybe try that one?

**Comment by bhallen** [comment]
Looks promising, but it doesn't fix the issue for me. You mean to just run this in the terminal and then try running pct_qt_debug.py again, right? Or should I put that line into a config file somewhere?

**Comment by mmcauliffe** [comment]
Yeah, it should just be run in the same terminal session as the call to pct_qt_debug.  Maybe try doing the ldd as in the accepted answer here (http://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without)? Might shed some sort of light, I haven't used ldd before.

**Comment by mmcauliffe** [comment]
Another possible fix: `LD_LIBRARY_PATH=~/miniconda3/envs/{env_name}/Library/lib/qt5/plugins/platforms:$LD_LIBRARY_PATH`

**Comment by bhallen** [comment]
Still no luck with those. I tried ldd and it didn't list any missing dependencies.

I'll give this a break and come back with fresh eyes later. Thanks for all the great suggestions!
