### ISSUE TITLE
Functional Load results reporting

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#516]
1. The new tooltip on the output minimal pairs file says that all spelling minimal pairs will be reported, even if "distinguish homophones" is not selected. While I believe that was true for the release version (which is what I used when I noticed the problem), it actually doesn't seem to be true on Develop. Specifically, the output of minimal pairs if "distinguish homophones" is not selected does leave out homophonous pairs (not sure how it's doing the selection) -- e.g., 'knot' / 'note' might be included, while 'not' / 'note' is not on the output list. I actually think it's probably more useful to truly include all the pairs, as the tooltip suggests, rather than having PCT arbitrarily select some of the ones to show. (In summary: The number of minimal pairs listed in the results box is currently accurate if distinguish homophones is NOT selected, i.e., the default...and it does match the output file, but the output file is NOT showing all actual minimal pairs as claimed.)

2. If "distinguish homophones" IS selected, the numbers in the results file and the output of minimal pairs list again match...but both are wrong. Specifically, PCT is counting spelling variants of HOMOPHONES as minimal pairs, in addition to homophonous minimal pairs. e.g., 'not' / 'note' and 'knot' / 'note' are both included, as expected, but 'not' / 'knot' is ALSO counted as being a minimal pair for [a] / [o] (which is clearly false). This needs to be fixed in both the result and the output file.

**Comment by bhallen** [comment]
Add a note at the top of the output file with minimal pairs stating that regardless of parameter values, all minimal pairs (even homophones) are listed.
