### ISSUE TITLE
List new features that need to be added to GUI

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#518]
- environment filters for FL
- dialogue window showing pairwise FLs when calculating relative FL
- force_quadratic argument to neighdens: add a checkbox in neighdens "force more general algorithm" which is greyed out unless using edit distance with max distance of 1. -> hook up to neighdens.neighborhood_density force_quadratic argument @jsmackie 
- visualizations (with mass FL calculation?)

**Comment by kchall** [comment]
there are other parameters you added a while ago, too, right? e.g. the ability to set environments for calculating FL?

**Comment by bhallen** [comment]
Good catch! I had forgotten to check through my commits to master back from before I merged it into develop. I've updated the original issue comment with the ones I had missed.

**Comment by bhallen** [comment]
For calculating segment pairs' FLs separately: make relative functional load functions return not just a value but rather a 2-tuple: (result, dict) where dict is {segment pair: its functional load}

**Comment by bhallen** [comment]
I've made this change to the return value of the relative function load functions, in addition to a general overhaul to the functional load return data structures and FL command line output file creation. But there's one bizarre error I'm getting when relative functional load functions (or the function that gets all pairwise FLs) try to iterate over the inventory:

```
/home/blake/repos/CorpusTools/corpustools/corpus/classes/lexicon.py in __iter__(self)
   1684 
   1685     def __iter__(self):
-> 1686         for k in sorted(self.segs.keys()):
   1687             yield self.segs[k]
   1688 

AttributeError: 'Inventory' object has no attribute 'segs'
```

Clearly Inventory objects /do/ have a segs attribute---it's part of how they're initialized. So what's happening here?? @jsmackie @mdfry
