### ISSUE TITLE
order result window headers

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#519]
check to see whether each result column has informative information or whether it's the same for all rows, and push all informative results columns to the left of the results window

preferably put the actual "result" calculation as the rightmost column of the left-hand informative columns

**Comment by mdfry** [comment]
Functionality is updated, now I need to update options-preferences with an option of how results are displayed.

**Comment by mdfry** [comment]
Updated in the gui preferences now - you can select to display unique results first or not (nothing fancy in between for now though)
