### ISSUE TITLE
questions re: Functional Load

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#530]
1. Our documentation indicates that the change in entropy version of functional load is simply a calculation of the difference in the entropies before and after merger. Surendran & Niygoi relativize this difference to the entropy of the original system. Do we not include that relativization? Do we want to?

2. We might want to think about making token frequency the default for change-in-entropy calculations, again following S&N.

**Comment by bhallen** [comment]
1. I just read through S&N. By relativization you're referring to the division of (pre-merger-H minus post-merger-H) by pre-merger-H, right? We didn't include this before now, but it seeme like we out to both for conceptual reasons and for the purposes of replication. So I just added a relevant parameter into the FL functions and the command line interface with commit 57b936296862c86129bec405af969fcbaac2beee . Please let me know if you disagree with the addition.

2. Token frequency is the default for both types of FL on the command line. If type frequency is the default in the GUI, then that'll need to be changed in the GUI code itself. The functional load analysis functions take a corpus that's already had its context (e.g. frequency type) specified. @jsmackie What do you think about changing the default in the GUI?

**Comment by kchall** [comment]
@jsmackie 
-add the relativization option to the GUI and make it the default
-change the default for delta-H FL to be token frequency

**Comment by mdfry** [comment]
@kchall Update documentation

**Comment by jsmackie** [comment]
The GUI changes are in place now.

**Comment by bhallen** [comment]
@jsmackie Looks great, thanks! Could you also make the type/token selection widget grey out when using minpair functional load?

**Comment by jsmackie** [comment]
Fixed!

**Comment by jsmackie** [comment]
With the GUI fixed, can we close this issue? @kchall @bhallen

**Comment by bhallen** [comment]
Yes, I think so.
