### ISSUE TITLE
Update screen shots in the docs

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#533]
The design of some things has changed since the last version, and we should put new screenshots into the documentation to reflect this.

- The picture of the screen for choosing a corpus now has a "Load with forced update" button that needs to be in the picture (text has been added to explain it already).

- There is no longer an option to select features and transcriptions independently. You have to select a feature file specifically. This means replacing any pictures of how to create a new corpus.

- The way that running text is displayed in the docs shows two panels: on the left a "classic" corpus and on the right the full text appears, with each word as its own widget. When I run the current version of PCT, I get something different: the right panel is the original running text, but formatted like the classic corpus in column format. This type of display is actually shown two pictures later in the docs for an example of loading from TextGrids.  Either we need a new screenshot for the running text, or there's a view option I don't know about. 

- The inventory charts have changed, so any images that include them should probably be changed

- The results windows probably need new screenshots too

**Comment by kchall** [comment]
I think I've got all the specific ones mentioned here. I haven't updated all the results windows, partially because in many cases, the screenshot doesn't even show all the results anyway, so not all changes would be visible. I'm going to close this one and we can open new issues if specific problems are noticed.
