### ISSUE TITLE
Neighbourhood density error

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#534]
On Develop branch, calculating ND for all words in the example corpus:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/ndgui.py", line 21, in run
    time.sleep(0.1)
NameError: name 'time' is not defined

**Comment by kchall** [comment]
OK, this isn't actually an ND error -- get the same thing with ProD:
Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/pdgui.py", line 21, in run
    time.sleep(0.1)
NameError: name 'time' is not defined

**Comment by bhallen** [comment]
I think this should be fixed in develop now. Could you give it another try, @kchall ?

**Comment by jsmackie** [comment]
I think that all of these problems were fixed in a recent commit where I removed some unnecessary use of the time module.

**Comment by bhallen** [comment]
Mmm, for what it's worth, when I was looking at the XXgui.py files today, they all still had a call to time.sleep in them, but no time imports. So since they all import .imports.*, I just added a time import to imports.py.
