### ISSUE TITLE
Bug in select segment by feature

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#540]
I've attached a picture of a few different outcomes of sorting the inventory by [high], using the example corpus. Each time that I load PCT, I get a different outcome. It is always at least partially correct but there are often segments missing. However, once PCT is loaded, the results are always the same - you have to close PCT and re-open it to get a different feature sort. Simply closing a corpus and then re-opening it doesn't change things.
![feature_class_problems](https://cloud.githubusercontent.com/assets/7388097/14969622/238c2c40-1078-11e6-80bc-1522c7aaaaef.png)

**Comment by jsmackie** [comment]
I've committed a potential fix for this. The old way of doing this involved calling a function find_min_feature_pairs, which looks for minimal contrasts. I don't think that minimal contrast is necessary in this case. If the user asks to break up the inventory based on, say, [high], we should just look for everything marked [+high] and put it in one group, and then put everything marked [-high] in another group (and likewise for any other possible feature value).

I created a new function InventoryModel.partition() which does exactly this. As far as I can tell, it is more accurate and consistent than the old way, although more testing is probably required.

**Comment by kchall** [comment]
This sounds great -- is it implemented in the GUI? I'm not getting any segments showing up when I enter for example [high] as a feature in the example corpus while adding sets of segments based on features in the FL dialog box.

**Comment by jsmackie** [comment]
Yes, this is definitely implemented in the GUI. Are you getting any kind of error message that prints in the background?

**Comment by kchall** [comment]
this is currently working for me...

**Comment by jsmackie** [comment]
@kchall Is it safe to close this issue yet? Or did someone else have problems with this as well?

**Comment by jsmackie** [comment]
And this is broken again for some reason. 

Traceback (most recent call last):
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\widgets.py", line 2029, in updateSegments
    feature_values = self.inventory.partition_by_feature(features, others)
  File "C:\Users\Scott\Documents\GitHub\CorpusTools\corpustools\gui\models.py", line 1633, in partition_by_feature
    if seg.features[match[1:]] == match[0]:
KeyError: 'voc'

**Comment by jsmackie** [comment]
Turned out to be an easy fix. The KeyError is raised because it's trying to check the features of a word boundary symbol, so now it just skips over that symbol.
