### ISSUE TITLE
Add to GUI: environment filters for FL

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#541]

**Comment by jsmackie** [comment]
I've run into a problem where the FL code seems to want a single EnvironmentFilter, but the widget for making filters returns a list of EnvironmentFilters. In any case, we would, in general, want users to be able to provide a list of environments. I think this means that the FL code has to be modified to include a loop (in one or more places) to check each of the incoming environments.

**Comment by bhallen** [comment]
Hm, interesting. What's the behavior when a user specifies multiple EnvironmentFilters? I imagine it does its functional load operation on any transcription that matches *any* of the EnvironmentFilters, right? If so, yes, I think this is an easy fix, and I'll get on it right away.

**Comment by jsmackie** [comment]
Line 140 in functional_load.py looks like this:

if any([s in all_target_segments and _fits_environment(tier, i, environment_filter) for i, s in enumerate(tier)]):
            
The _fits_environment() function calls another function _make_environment_re(environment_filter), which has this bit of code on line 43:

re_lhs = ' '.join(['('+('|'.join([seg for seg in position])+')') for position in environment_filter.lhs])

This raises an AttributeError "list has no attribute .lhs".

I think what need to happen is that we need to feed the EnvironmentFilters one at a time into _make_envrionment_re(). Does that make sense? If you don't mind, I'm going to re-assign you to this issue for now.

**Comment by bhallen** [comment]
@jsmackie Great, yes, it looks like that was the right thing to do. I just pushed a commit fixing this. If everything is set up correctly to handle this on the GUI side, then feel free to close this issue.

**Comment by jsmackie** [comment]
@bhallen Thanks! I've fixed up the GUI part, as far as I can tell.  I don't know what the results should look like for this analysis though, so maybe I've missed something. Do we have a test written for FL including environment filters?

Also, the Results window doesn't mention the environment - should that be included somewhere? @mdfry what do you think?

**Comment by bhallen** [comment]
Hm, I don't believe we have any environment filter tests right now. Maybe we can add some next Friday.

**Comment by jsmackie** [comment]
I'm going go to close this issue, since it mentions the GUI in the title and that part is finished. I'll add the bit about testing and results elsewhere.
