### ISSUE TITLE
Add to GUI: force_quadratic for neighdens

### ISSUE THREAD

**Issue by bhallen** [PhonologicalCorpusTools/CorpusTools#542]
force_quadratic argument to neighdens: add a checkbox in neighdens "force more general algorithm" which is greyed out unless using edit distance with max distance of 1. -> hook up to neighdens.neighborhood_density force_quadratic argument

**Comment by jsmackie** [comment]
As far as tooltips go, what should we tell the user about the force_quadratic option? It sounds weird to simply offer the option of a slower algorithm.

**Comment by bhallen** [comment]
How about this:

"Unless this box is checked, PCT will use an algorithm specific to calculating neighborhood density based on a maximum edit distance of 1. This algorithm may be faster than the general-purpose algorithm, especially on very large corpora."

By the way, the checkbox field should be greyed out _unless_ using edit distance with a maximum distance of 1, if possible.

**Comment by jsmackie** [comment]
I can make the checkbox grey out if choosing an option other than edit distance (which is what happens already). I couldn't figure out how to get an automatic grey-out when the distance isn't 1. Instead, I added a check to FLDialog.generateKwargs(), which is called when the user clicks "Calculate". If the distance != 1, then the box is effectively unchecked, and a False value is sent to the fl function.

**Comment by jsmackie** [comment]
I should also say that I decided to use a checkbox that says "Use quadratic-time algorithm", rather than "Use general algorithm" because that matches the parameters in the FL function better. I think it's also more intuitive for the tooltip to read "If you select this option..." rather than "Unless you select this option...".

**Comment by bhallen** [comment]
That all sounds good to me. Thanks, Scott!
