### ISSUE TITLE
updating docs?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#550]
Scott updated the "environment_selection.rst" file (step 3 should now have information about adding features or adding segments), and this has clearly been updated on the GitHub develop source files. But the URL version (http://corpustools.readthedocs.io/en/develop/environment_selection.html) has the old, non-informative step 3. Any ideas what might cause this?

**Comment by jsmackie** [comment]
In the left column of the page you linked, at the very bottom, there is an option to change branches. My edit appears if you switch  to "master". We are going to synch up "master" and "develop" eventually, when we release the next version, so this won't be a problem any more. In the future, I'll remember to edit the "develop" version of the docs, not "master".
