### ISSUE TITLE
Only one Transcription per corpus?

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#560]
IPHOD (the text file) has two "transcription" columns - one with stressed marked, one without - but only one of them can be marked as Transcription type in the corpus loading window. The other would have to be marked "Other (character)". When PCT loads the corpus, only the Transcription type is available in analysis functions. The other is not. 

This needs to be fixed so that either (a) more than one Transcription per corpus is allowed, or (b) the "other" type can be selected as a Tier from within an analysis. Option (b) is probably simpler.

**Comment by jsmackie** [comment]
This is mostly working now. A corpus can now have a default transcription or spelling, as well as a list of alternative transcriptions and spellings. Alternative transcriptions appear as their own column, and show up in analysis windows as selectable tiers.

This required making some changes to the Corpus object, which also breaks backward compatibility, so a next step is to fix this.

There are also a few functions inside of PCT that don't work entirely (for instance, adding a word with a segment that appears in the default transcription but not the alternative one).

**Comment by kchall** [comment]
I'm still checking this out myself, and it basically seems to work! -- but one thing that would be helpful is to have the default settings be slightly different from what they are now -- e.g., tiers that are automatically detected as transcription get set to be "Transcription (alternative)" and it seems like it would make more sense for them to be "Transcription (default)" -- that way, if there's only one transcription column, no changes need to be made. Same with "spelling" (should default to "Orthography (default)" not "Orthography (alternative)") and "frequency" (should default to "Numeric").

**Comment by kchall** [comment]
Hmm, ok, loading a corpus basically seems to work, but we'll need to do some things to make it link in correctly with the pronunciation variants tools, which were originally created basically for TextGrid and Buckeye formats. 

I created a sample csv corpus called "tiered_with_alt_prons.txt" in the CorpusTools/tests/data/csv folder. Basically, this corpus has three words in it, each of which has multiple pronunciations. Each line of the file has one pronunciation of the word, in the "actual transcription" column, but also lists the word itself in the "canonical transcription" column. Ideally, if we set the canonical transcriptions to be associated with the lexical item, while the actual transcriptions are allowed to vary within lexical item, we'd get a corpus that treats the actual transcriptions as pronunciation variants (e.g., in the main corpus window, we'd get only three entries, one for each canonical transcription, and right-clicking would show the variants; in analysis windows, we could select from among the different pronunciation variants options). 

Instead, what we get is basically what you'd expect -- that is, the main corpus window shows the corpus as it was in the original text file, with one line per entry, and that means that we're not actually grouping the words together by their canonical transcription. 

This may be more than we can really handle at the moment, though. **What I would like is to prioritize making sure our original pronunciation variants with TextGrids work.** 

Even for cases where the alternative transcription column is simply a different system (e.g., IPA vs. Arpabet), it's not clear to me that getting everything to work will be straightforward. I also created a sample csv corpus called "tiered_with_alt_trans.txt" in the CorpusTools/tests/data/csv folder. This one has two transcriptions of the same words (no pronunciation variants). I can get it to load well in the main corpus window, but in an analysis, while I can select the alternative transcription, I don't get any of the symbols from that transcription, and there's no way to switch the inventory view from one transcription column to the other. That's to be expected at this point, but it seems like it will be quite a lot of work to achieve it, and again, I don't think that needs to be a high priority given our time constraints.

**Comment by jsmackie** [comment]
"one thing that would be helpful is to have the default settings be slightly different from what they are now"

I noticed this problem too, and it's something I'm aiming to fix today.

"Ideally, if we set the canonical transcriptions to be associated with the lexical item, while the actual transcriptions are allowed to vary within lexical item, we'd get a corpus that treats the actual transcriptions as pronunciation variants"

I didn't know that this wasn't working, so I'll have a look at it today too.

"Even for cases where the alternative transcription column is simply a different system (e.g., IPA vs. Arpabet), it's not clear to me that getting everything to work will be straightforward."

I'm going to make this impossible for now, and consider implementing it later. When the user makes a corpus from a file, there is a check to see if all of the transcription symbols appear in the selected feature file. If any symbols don't match, they get default values of 'n' for all features and the user is alerted about this (and has the option of cancelling and selecting a different feature system). I just need to extend this check to all of the transcriptions; right now only the default it checked.


"I don't get any of the symbols from that transcription, and there's no way to switch the inventory view from one transcription column to the other."

Inventory charts in the main window will always display the default transcription's inventory, and only the default inventory's table should be open for editing. In an analysis window, users should be able to see (but not edit) the inventory of alternative transcriptions. This can be accomplished by simply feeding the alternative inventory to the default inventory table's sort function. That is, we sort the alternative inventory based on the default inventory's row/column settings. Some alternative segments (possibly all of them) will end up in the uncategorized tab, but there's not much to be done for that right now. I think this can be a relatively quick fix.

**Comment by kchall** [comment]
Sounds good to me. Found another bug though (sorry!):

I was trying to re-create the example of getting pronunciation variants from an inter-linear gloss file, which we describe in the documentation under "Creating Pronunciation Variants" (http://corpustools.readthedocs.io/en/latest/pronunciation_variants.html).

The test file is available here: CorpusTools/tests/data/ilg/ilg_with_pronunc_vars.txt

I tried to load it with Line 1 being Orthography (default) [associated with lexical items), Line 2 being Transcription (default) [associated with lexical items], and Line 3 being Transcription (alternative) [allowed to vary within lexical items], and got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 85, in run
    corpus = load_discourse_ilg(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 235, in load_discourse_ilg
    discourse = data_to_discourse(data, lexicon, call_back=call_back, stop_check=stop_check)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/helper.py", line 416, in data_to_discourse
    if len(seq) > 0 and seq[0].begin is not None:
AttributeError: 'str' object has no attribute 'begin'

**Comment by kchall** [comment]
[tiered_with_alt_prons.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/342239/tiered_with_alt_prons.txt)
[tiered_with_alt_trans.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/342240/tiered_with_alt_trans.txt)

**Comment by jsmackie** [comment]
Do a "roll-back" to allowing only one transcription per corpus for now (others must be marked as "other (character)".

**Comment by jsmackie** [comment]
Multiple transcriptions (or spelling) should be working now. There isn't an option to select "default" or "alternative". Instead, whatever transcription/spelling column comes first is considered the default and the rest are alternatives. The default really only matters for the purposes of the inventory chart.
