### ISSUE TITLE
Neighbourhood density bug?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#567]
Tried to calculate ND for all words in the example corpus, based on transcription, using Edit distance with a threshold of 1 (to replicate the documentation); got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/ndgui.py", line 61, in run
    stop_check = kwargs['stop_check']
  File "/Users/KCH/Desktop/CorpusTools/corpustools/neighdens/neighborhood_density.py", line 64, in neighborhood_density_all_words
    setattr(w.original, corpus_context.attribute.name, res[0])
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by jsmackie** [comment]
You can calculate ND now, but the results are returning all 0s for the example corpus. Is that correct? I tried this with lemurian, and I get mostly 0s but a few 1s, so it's not entirely broken...

**Comment by kchall** [comment]
I just tried it and got mostly 0s but two 1s in the example corpus -- mata / nata as a minimal pair should each show up with an ND of 1. Since this is working for me, I'm going to close it, but you might want to doublecheck that you get the right thing, too?
