### ISSUE TITLE
FL results table

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#568]
There's a new option for delta-H about normalizing the results; the default is to normalize. But, there needs to be a column in the results table that indicates what the actual value for that option was for any given analysis.

**Comment by jsmackie** [comment]
This is fixed, except that the results table is now so long it doesn't fit nicely on screen any more

**Comment by kchall** [comment]
Hmm, this fix isn't exactly what I had in mind -- currently, there are two "Results" columns, one for the requested result, and one for the non-normalized result, which returns an "NA" if the requested result was already non-normalized. Could we just have a single "Result" column that returns the requested result, and then another column that indicates whether the result was normalize (i.e., yes or no)?

Relatedly, there's already a column that indicates whether the result was relativized, which is intended for the minimal pair algorithm. But it would be fine to just use that column and say "yes" whenever the result is normalized somehow and "no" when it's not, regardless of algorithm. Otherwise, if we have two separate columns, one for each algorithm, we should make sure that the other column indicates "NA" if it wasn't applicable (currently it says "yes" even if delta-H is used, which is confusing).
