### ISSUE TITLE
FL Bug

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#569]
Calculating the delta-H FL on a single segment (B) in the IPHOD corpus:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/flgui.py", line 51, in run
    output_filename = outf,**kwargs)
TypeError: relative_deltah_fl() got an unexpected keyword argument 'output_filename'

**Comment by jsmackie** [comment]
This should work now, although for some reason the progress bar freezes while this function is running (I can see stop_check calls in there, but they don't seem to do anything). Cancelling may raise a PCTError.
