### ISSUE TITLE
[h] is uncategorized in SPE feature system

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#584]
or rather [h] doesn't get categorized as a glottal fricative in auto-categorize with SPE features

**Comment by stannam** [comment]
(copied from comments in #748)

* [h] and [ɹ] should end up uncategorized in the current categorization.
    - [h] is [-consonantal], thus should NOT be one of the consonants.

Note: SPE classifies [h] as a glide, not fricative. (p. 354)
![image](https://user-images.githubusercontent.com/43150234/106861426-95c9b680-667a-11eb-9ad0-aa228c5359fc.png)
