### ISSUE TITLE
Error with re-naming spelling tier

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#589]
When creating the ilg_sample corpus, if the name of the Spelling tier isn't "Spelling," the spelling column ends up blank, though no error is generated. It is called whatever was specified in the loading window.  (The second "spelling" column shows up, with entries, called "Spelling," and in third position.)

When creating the csv_sample corpus, if the name of the Spelling tier isn't "Spelling," the corpus loads correctly, the spelling column isn't blank, but isn't re-named.

**Comment by jsmackie** [comment]
this should be fixed in the most recent commit
