### ISSUE TITLE
Running text, ILG, Buckeye corpora don't have their word-in-context versions

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#590]
When creating a running text corpus, an ILG corpus, or the Buckeye corpus, the corpora now load, but we're missing the right-hand window / pane that showed the original text of the corpus in linear order. (All we get is the standard corpus view.)

**Comment by jsmackie** [comment]
This second pane appear now, although the pronunciation variants are not correctly grouped together

**Comment by jsmackie** [comment]
This problem was due to code that was commented out. Uncommenting the code allows the in-context widget to appear, but it is extremely small (roughly one word wide and high) and it appears in an unusual place on the page This may not be fixable for v.1.2

**Comment by kchall** [comment]
The pane works ok and looks fine for me, for the ILG corpus. But everything is blank for the Buckeye corpus?
