### ISSUE TITLE
Missing pronunciation variants

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#592]
In creating the Buckeye_sample corpus, the corpus loads, but right-clicking a word and asking for its pronunciation variants shows an empty window. No error is generated.

**Comment by jsmackie** [comment]
The Buckeye corpus loads and I can get a pronunciation variants window to appear, but apparently everything has 1 variant. Is this correct? I suspect not...

**Comment by kchall** [comment]
Nope, there should definitely not just be one variant per word -- you can always check the results for the word "probably" when in doubt. ;-)

**Comment by jsmackie** [comment]
Sorry, when said Buckeye, I meant the file located at \CorpusTools\tests\data\buckeye\test.words (which doesn't contain "probably").
