### ISSUE TITLE
Manage inventory chart: feature values missing

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#600]
In trying to add a column in the feature inventory chart for the csv_sample corpus (basically, the example corpus), I get a dialogue window that lists the features but doesn't give any options for adding either positive or negative values -- the only buttons are the "remove" buttons. See screenshot.

![image](https://cloud.githubusercontent.com/assets/7317450/18145131/b238530a-6f7e-11e6-8e5a-f5a4cf8d784a.png)

**Comment by jsmackie** [comment]
I'm not able to replicate this bug on my own computer. I actually do get the set of buttons in the centre. Does this only happen with the example corpus you loaded, or does it happen with all corpora?

**Comment by kchall** [comment]
Hmm, it seems to work for me in the actual example corpus, but not in the csv_sample (created from the raw .csv file).

**Comment by kchall** [comment]
This is still happening for me with the attached .txt file.


[csv_sample.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/528382/csv_sample.txt)

**Comment by kchall** [comment]
This seems to have been a problem with the old ipa2spe file; it's now working ok.
