### ISSUE TITLE
PCT not importing .csv files

### ISSUE THREAD

**Issue by dvdmrn** [PhonologicalCorpusTools/CorpusTools#604]
I'm trying to import a very simple corpus and I keep getting the same error:

```
Something went wrong that wasn't handled by PCT:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/corpustools-1.1.0-py3.5.egg/corpustools/gui/iogui.py", line 107, in run
    corpus = load_corpus_csv(**self.kwargs)
TypeError: load_corpus_csv() missing 1 required positional argument: 'trans_delimiter'

```
As a test, I tried downloading an example toy corpus (which worked fine), and then saving it as a .csv, and then importing it from my local hard drive and I get the same error. 

I've set spelling annotation type as 'orthography',  transcription as 'Transcription' (with a . transcription deliminter), and frequency as numeric.

I'm running Ubuntu 16.04 (64-bit)

Here's an example of the simple corpus I'm trying to import:

```
spelling,transcription,frequency
mner ,m.n.e.ɹ.m.n.e.ɹ,1
chuggachugga,t.ʃ.ú.g.a.t.ʃ.u.g,1
shiuuu ,ʃ.i̥.u̥.u̥,1
badumbadum ,b.á.d.ɐ̀.m.b.à.d.ɐ́.m,1


```
And here's an example of the example corpus that I downloaded and tried to import
```
spelling,Transcription,frequency
atema,ɑ.t.e.m.ɑ,11
enuta,e.n.u.t.ɑ,11
mashomisi,m.ɑ.ʃ.o.m.i.s.i,5
mata,m.ɑ.t.ɑ,2
nata,n.ɑ.t.ɑ,2
sasi,s.ɑ.s.i,139
shashi,ʃ.ɑ.ʃ.i,43
shisata,ʃ.i.s.ɑ.t.ɑ,3
shushoma,ʃ.u.ʃ.o.m.ɑ,126
ta,t.ɑ,67
tatomi,t.ɑ.t.o.m.i,7
tishenishu,t.i.ʃ.e.n.i.ʃ.u,96
toni,t.o.n.i,33
tusa,t.u.s.ɑ,32
ʃi,ʃ.i,2
```

**Comment by dvdmrn** [comment]
Just as a quick follow up I suspect this might be a problem with the GUI as I can load in .csv files fine with `corpustools.corpus.io.csv.load_corpus_csv(...)` in python

**Comment by kchall** [comment]
Hmm, again, can you try on the Develop branch? I can't replicate the error with your sample corpus. It loads, and looks correct:
![image](https://cloud.githubusercontent.com/assets/7317450/18651544/cf2d1674-7e80-11e6-9d17-d3fe5a80c798.png)

**Comment by dvdmrn** [comment]
Hmm I reinstalled from the develop branch and when I try and run pct from terminal I get the error: `ImportError: No module named 'corpustools.tactics'`. I tried running as sudo as well so this doesn't seem to be a permissions thing.

**Comment by kchall** [comment]
Hmm, none of us has tried launching PCT from the Terminal. (except @bhallen?) What .py program were you running? The one you want to try is pct_qt_debug.py (in CorpusTools / bin).

When I tried it, I got a different error:

Kathleens-MacBook-Pro-2:bin KCH$ python -3 pct_qt_debug.py
Traceback (most recent call last):
  File "pct_qt_debug.py", line 5, in <module>
    import corpustools.gui.main as Main #import MainWindow,QApplicationMessaging
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 5, in <module>
    import corpustools.gui.modernize as modernize
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/modernize.py", line 2, in <module>
    from corpustools.corpus.classes.lexicon import Corpus, Inventory, Segment, FeatureMatrix, Word
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/__init__.py", line 2, in <module>
    from .lexicon import (Corpus, Word, Environment, EnvironmentFilter, FeatureMatrix,
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 10, in <module>
    from corpustools.exceptions import CorpusIntegrityError
  File "/Users/KCH/Desktop/CorpusTools/corpustools/exceptions.py", line 318
    'an environment not included in the list you selected.'),file=f)
                                                                 ^
SyntaxError: invalid syntax


If you launch a code editor (e.g., Idle) and run the pct_qt_debug.py from that, do you get the same problem as you had originally?

**Comment by bhallen** [comment]
@dvdmrn I'm not familiar with the `tactics` submodule (maybe it's new?), but have you tried manually setting your PYTHONPATH to include the top level of the repo?

@kchall It sounds like you might've been running that with Python 2.*. Have you tried Python 3?

**Comment by dvdmrn** [comment]
Update: this issue has been solved on the develop branch
