### ISSUE TITLE
error in phonological searches

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#607]
I searched for [u * ɚ] or [ʊ * ɚ] sequences in the IPA version of the IPHOD corpus (and there are words transcribed this way -- e.g., trooper, cooker), and the search just came up as completely blank. Not sure if this is tied to the wildcard?

**Comment by kchall** [comment]
Similarly true with wildcard searches in the example corpus.

**Comment by jsmackie** [comment]
I can't replicate this bug (of course....)

![image](https://cloud.githubusercontent.com/assets/7388097/19426856/bd82f504-93f4-11e6-853d-e88f65147a44.png)

![image](https://cloud.githubusercontent.com/assets/7388097/19426864/c7b34d30-93f4-11e6-9c09-bb3d26c1bfb8.png)

**Comment by kchall** [comment]
Can you replicate it in the IPHOD corpus? I just tried again in the example corpus, and it seems to work ok. But I still get nothing when I do the above search in IPHOD (and no error message).

**Comment by kchall** [comment]
magically fixed?
