### ISSUE TITLE
inventory issues

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#612]
1. Load the csv_sample.txt corpus with no feature system associated with it (this is one of the sample files in the public PCT Dropbox folder). Specify that the transcription delimiter is a period.

2. The corpus summary window should show all of the segments listed under "uncategorized" in alphabetical order. Instead, the inventory window isn't even available:

![image](https://cloud.githubusercontent.com/assets/7317450/20329319/6a455868-ab4c-11e6-8d3e-a677ff3291f0.png)

3. Try to associate the ipa2hayes feature system to the corpus. Check the corpus inventory coverage. The following message appears, even though all of these segments are properly in the ipa2hayes feature file:

![image](https://cloud.githubusercontent.com/assets/7317450/20329360/9e84703c-ab4c-11e6-8a2c-864ed80dc452.png)

4. The corpus summary window IS now correct, even though the above message seems to indicate that it wouldn't be because not all the segments are covered:

![image](https://cloud.githubusercontent.com/assets/7317450/20329379/bf6f3872-ab4c-11e6-91d6-23e2b27b5e8f.png)

5. Note: if you load the csv_sample.txt corpus with the ipa2hayes feature file from the get-go, and check the corpus inventory coverage, PCT correctly recognizes that all segments are covered:

![image](https://cloud.githubusercontent.com/assets/7317450/20329432/03583b06-ab4d-11e6-94d3-856b692240bd.png)

**Comment by jsmackie** [comment]
The missing inventory chart is not a bug, this is the expected behaviour of the program. If you don't load a corpus with a feature system, then you can't get inventory charts. In order to load an inventory chart, PCT needs information about features, and if there's no feature system then there's no way for PCT to get this information.

What you mention in point 3, on the other hand, is a bug.  I'll look into what's causing this to happen

**Comment by jsmackie** [comment]
Well that was a quick fix. The code wasn't checking the right set of features. This seems to work now, except for the weird problem with the 'g' symbol.

**Comment by kchall** [comment]
I'm ok with an inventory chart not being available, but just going to note: this is different behaviour than we used to have. That is, it used to be that the segments would all show up, in alphabetical order (e.g., these could be under the "uncategorized" tab). I'll update the docs.
