### ISSUE TITLE
implicit merging of homographs

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#615]
If a user uploads a .csv-style corpus that has spelling, transcription, and frequency, but happens to have two words that are spelled the same way (even if their transcriptions differ), PCT will only read one entry for them. 

For example, the attached 'homographs.txt' file has two words, 'bow' and 'advocate,' that each have two different transcriptions. In creating a corpus, PCT only counts the first of each pair, and simply deletes the second (it doesn't even merge the frequency counts). 
[homographs.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/596198/homographs.txt)

This is probably tied to the options about letting transcriptions vary within lexical items. Basically, I think that if a user is uploading a .csv file, we might want to eventually add the capability to have pronunciation variants, but it would probably be easiest if we just don't currently have that option. Then, if the transcription is set to be associated with the lexical item (the usual for "canonical" pronunciations, i.e., not varying within lexical items), I think it's more reasonable to assume that each row in a .csv file is to be treated as a lexical item. [I guess we could make this an option for .csv corpora, i.e., "treat lines as separate lexical items." If we do want to continue the option of collapsing identically spelled items as the same lexical item, PCT should collapse the frequencies of the words into a single number.] (Note that currently, if you set the pronunciations to vary within lexical items with a .csv file, it doesn't actually set it up properly with lexical items and pronunciation variants. So again, I think the easiest thing to do is to turn off this option for .csv corpora, and also make sure that we treat separate line entries as separate lexical items.)

**Comment by jsmackie** [comment]
It turns the corpus.add_word() function already had an allow_duplicates argument, that was intended for exactly this situation. The code adding new words from a csv was calling the function with its default value of False. I changed things to call the function with a True value instead, and that seems to fix things, or at least I can see the different transcriptions and frequencies in the main window.

**Comment by kchall** [comment]
This seems to be working from what I can see? But I'll leave it open based on your comment above.
