### ISSUE TITLE
change feature system / lose inventory specifications

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#618]
-Load a corpus with a custom feature system. (e.g. the Hong Kong Cantonese corpus)
-Go in to the "Manage Inventory Window" and edit the categories to set up the whole inventory.
-Realize that you've mis-categorized a segment with some feature value.
-Go in to "edit feature system" and change the value. Save the changes by overwriting the file.
-All of the inventory set-up is entirely lost. That is, it no longer knows e.g. that stops are [-continuant], labials are [+labial], etc., even though all you've done is changed the specific feature value of a particular segment. This shouldn't happen.

**Comment by jsmackie** [comment]
This is fixed, however, after you go back to the inventory window, you may have to click the "update features" button in order for you to see the change come into effect. I've added a message explaining this into the inventory window.

**Comment by kchall** [comment]
Just to confirm: yes, this is working! Thanks!
