### ISSUE TITLE
KL Divergence bug

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#631]
Tried to run KL divergence on the IPHOD corpus with the default arpabet2hayes feature system (on all pairs of consonants differing in one major phonetic characteristic, e.g. [B]/[P] or [B]/[D] or [B]/[M]). Minimum word frequency was set to 1; type frequencies were used; environments were left-side only. The following error occurs:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/klgui.py", line 36, in run
    call_back = kwargs['call_back'])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/kl/kl.py", line 135, in KullbackLeibler
    is_spurious = _check_spurious(ur, sr, corpus_context)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/kl/kl.py", line 158, in _check_spurious
    seg_diff = diff(ur, sr)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/kl/kl.py", line 154, in <lambda>
    diff = lambda flist1,flist2: len([f1 for f1,f2 in zip(sorted(flist1.values()),
AttributeError: 'Segment' object has no attribute 'values'

**Comment by jsmackie** [comment]
I'm not able to replicate this bug. Running KL with IPHOD gives me a proper output (screenshot attached). Have you downloaded a fresh copy of IPHOD?
![kl screenshot](https://cloud.githubusercontent.com/assets/7388097/22217727/090eb77c-e159-11e6-8677-998def9391c9.png)

**Comment by kchall** [comment]
Hmm, great...I definitely thought I had a current version, but you're right, downloading it afresh seems to have solved the problem. Thanks!
