### ISSUE TITLE
atypical features not working

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#633]
Trying to create a corpus of Laurentian French. When the feature system was entirely deprecated, many of the segments (e.g., [E]) didn't show up even in the "uncategorized" tab of the inventory window. With a full set of vowel features, all segments show up. But, using the [specialC] feature to separate out [v], [z], [Z], and [R] doesn't work. I can use it to set up the consonant inventory window, but selecting segments for +specialC or -specialC doesn't actually do anything.

fully deprecated feature set:
[CustomFeatures.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/775095/CustomFeatures.txt)

slightly expanded feature set:
[LF_Features_for_KCH_transcription.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/775089/LF_Features_for_KCH_transcription.txt)

I'll e-mail you the corpus.

**Comment by kchall** [comment]
Perhaps related:
-In the executable version of PCT: I created the closed monosyllable Laurentian French corpus and associated a Hayes-based feature system. When the corpus is loaded and an analysis function is selected, the warning message about needing a feature system before analyses can be done is provided -- even though going in to "view/change the feature system" confirms that there is a complete system there, and all segments are specified for features. Going to "manage inventory window" fails (nothing happens), and no error message is given.
-Doing exactly the same thing in the develop branch version does work, and the feature system is associated with the corpus. Analysis functions are possible.

-That said, the Hayes-based system I used (which does have all the same features as the regular built-in Hayes systems we use, but in a different linear order) does not allow "Autocategorize" to work. The "manage inventory window" does open, and I could hand-organize the segments, but Autocategorize does nothing (even when the default features for Cs and Vs are added, and "Update features" has been used).

-If I go back to the executable version of PCT and load the corpus created in the develop branch version, PCT does "remember" that the feature system exists, and now the executable version works like the develop version -- i.e., analyses can be run, but the autocategorize function fails.

**Comment by kchall** [comment]
I also note that it's still the case that the "SpecialC" feature doesn't work -- e.g., if I try to select segments that are + or - [SpecialC], nothing happens, even though segments are specified for it and other features (like [voice]) do work).

**Comment by kchall** [comment]
Another feature file issue:
I just tried to create a custom feature file from a tab-delimited text file (
[gitksan2hayes_orth_cap_letters.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/840054/gitksan2hayes_orth_cap_letters.txt)
), and got the following error (which I was asked to report to the developers). This happens in both the executable and in the current Develop branch.

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 29, in run
    system = load_feature_matrix_csv(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/csv.py", line 243, in load_feature_matrix_csv
    newline[k] = v[0]
IndexError: string index out of range

**Comment by jsmackie** [comment]
These are the expected features for autocategorize:

{'hayes' : ['consonantal', 'labial', 'coronal', 'labiodental', 'anterior', 'dorsal', 'back', 'sonorant', 'delayed_release', 'nasal','continuant', 'trill', 'tap','lateral', 'front', 'back', 'high', 'low'],

 'spe' : ['voc', 'ant', 'cor', 'high', 'low', 'back', 'son',
                                                          'lat', 'nasal']}

**Comment by kchall** [comment]
Using these features works for autocategorizing the Gitksan and Laurentian French inventories (at least in the bug_fixes branch; I couldn't even access the "manage inventory" window in the Gitksan corpus with the released version, but fixing it in the bug_fixes branch also then allowed me correct access in the released version). The "extra" features, though, still don't work -- e.g., I can't select segments for a search or an analysis that are [+specialC], even though PCT clearly "knows" this feature is present because it does fill it in:

![image](https://cloud.githubusercontent.com/assets/7317450/24174149/6dbbdc7a-0e4c-11e7-960b-ec6bbeb98801.png)

In sum -- I think the current system will work for all the issues in this thread except the original one, i.e., getting "special" features to be used accurately.

**Comment by kchall** [comment]
I updated the transcriptions_and_feature_systems.rst documentation file on the bug_fixes branch to reflect the features needed for Auto-categorize to work.

**Comment by jsmackie** [comment]
I figure out the problem here: the code that matches features was converting everything to lowercase, and your custom features each had a capital letter in their name, [rvzZ, specialC]. I just removed the forced lowercasing, and it seems to work again.
