### ISSUE TITLE
mismatches in inventories

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#641]
In the LF_syllables_retranscribed corpus, there are mismatches among the three places where inventories are listed (all segments are uncategorized, but do have features):
1. The "manage inventory chart" has only 15 segments listed in the uncategorized section;
2. The inventory chart (e.g. when doing a phonological search and adding segments) shows 31 segments;
3. There are actually 40 segments used in the corpus (as evidenced by the "View / change feature system window).

This makes it possible to select the "missing" segments only by using their feature specifications.

**Comment by kchall** [comment]
OK, the "manage inventory chart" and "view / change feature system" windows now match (with 41 segments each), but the inventory charts when doing a summary or implementing an algorithm are still missing.

**Comment by kchall** [comment]
Seems to be tied to the use of NaN for token frequencies in this corpus. e.g. [h] and [c] ONLY have NaN values; these crash the summary window. In phonological searches, others return NaN token frequencies even when they are not all NaN.

**Comment by kchall** [comment]
This does not actually seem to be fixed. Now, clicking on any segment (including [h] and [c], but also other segments) seems to put PCT into a (long? endless?) counting loop. In the background, it is individually printing every symbol (possibly going through every transcription in the corpus? but I haven't let it run long enough to see for sure whether it will eventually stop or not). The summary window is frozen and does not display the actual frequencies.

![image](https://cloud.githubusercontent.com/assets/7317450/24637831/dac6c90a-1898-11e7-8ba7-2e3f402180e6.png)

**Comment by kchall** [comment]
Update! It's not an endless loop -- it took about 20 minutes, but it did finally stop and show me the type and token frequencies for [p]. 

![image](https://cloud.githubusercontent.com/assets/7317450/24638106/bb0634fa-189a-11e7-97dd-fcc329ae96cf.png)

**Comment by jsmackie** [comment]
This was due to an extraneous print() call somewhere in PCT. That's been removed, so this shouldn't come up again.
