### ISSUE TITLE
Neighbourhood density algorithm: homophones

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#648]
include an option for whether homophones (lexical items with the same pronunciation) are counted as one neighbor or separate neighbors

**Comment by jsmackie** [comment]
I've added a checkbox to the ND dialog that says "collapse homophones into a single neighbour". If checked, then words with identical transcriptions are not counted as separate neighbours (spelling is ignored). If unchecked, then everything is a potential neighbour.

**Comment by kchall** [comment]
Hmm, when I click on "Calculate neighbourhood density" to test this out, I get the following error and the dialogue box doesn't even open:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 231, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 759, in neighDen
    dialog = NDDialog(self, self.settings, self.corpusModel, self.inventoryModel, self.showToolTips)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/ndgui.py", line 174, in __init__
    self.oneWordRadio.setChecked()
TypeError: QAbstractButton.setChecked(bool): not enough arguments

**Comment by kchall** [comment]
needs to be updated so that homophones that are spelled identically to each other can also be collapsed or not collapsed, as per user's choice (currently, if they're spelled the same AND homophones, PCT automatically collapses them as 1 neighbour)

**Comment by kchall** [comment]
[example_with_homophones.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/1459068/example_with_homophones.txt)

In this corpus, <nata> should have two neighbours if homophones are collapsed ([m.a.t.a] and [s.a.t.a], but should have four neighbours if homophones are not collapses (<mata>, <mata>, <sata>, and <satha>). (Currently, not-collapsing results in 3 neighbours: <mata>, <sata>, and <satha>.)

**Comment by kchall** [comment]
maybe also allow users to specify if the output file with neighbours displays spelling or transcription?
