### ISSUE TITLE
phonotactic probability error

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#652]
From a user:

I was just trying to calculate phonotactic probability and got this error...

Traceback (most recent call last):
File "corpustools\gui\ppgui.py", line 49, in run
File "corpustools\phonoprob\phonotactic_probability.py", line 47, in phonotactic_probability_all_words
File "corpustools\phonoprob\phonotactic_probability.py", line 114, in phonotactic_probability_vitevitch
File "corpustools\contextmanagers.py", line 171, in get_phone_probs
File "corpustools\contextmanagers.py", line 171, in <dictcomp>
ZeroDivisionError: float division by zero

I had it set to calculate over tokens, not types, in case that matters... When I did it over types, I didn't get the error.

**Comment by jsmackie** [comment]
Can we find out which corpus and feature system the user had? I tried this out with example, lemurian, and IPHOD and they all work fine.

**Comment by kchall** [comment]
I believe this is the Korean corpus -- I can send you the files by e-mail.

**Comment by kchall** [comment]
I like the basic idea of the fixes, in terms of adding an option for logging the frequency if token frequencies are used. But there are still some issues:
-the default setting should be biphone, token, logged (currently, it's biphone, type)
-when biphone or single-phone type frequencies are selected, it's still returning the non-logged token frequencies instead (as can be seen in the attached screenshot); note that it is correct in the calculation for the non-logged token versions, but repeats the same number for the type versions
-the output window should specify whether the frequencies were logged or not (in the attached screen shot, the first token frequencies are the logged versions and the second ones are the non-logged versions)

![image](https://user-images.githubusercontent.com/7317450/32589977-a903b726-c4cc-11e7-8b2e-63c8d308be76.png)

**Comment by kchall** [comment]
Also, just confirming that I think the original issue (of division by zero) has been fixed, though the documentation needs to be updated to (1) specify that PCT takes natural logs, but the calculations end up the same regardless, because of the division; and (2) also specify that token frequencies of 1 are automatically replaced with 1.000001 to avoid division by zero. @kchall
