### ISSUE TITLE
Phonological Search

### ISSUE THREAD

**Issue by jsmackie** [PhonologicalCorpusTools/CorpusTools#655]
- Make sure searches load properly (COMPLETE)
- Add "delete" button (COMPLETE)
- Add multi selection for saved searches (COMPLETE)
- Prevent cells from being editable (COMPLETE)

**Comment by YuHsiangLo** [comment]
- Add a word frequency filter
- Add a phoneme number filter
- Add a syllable number filter (afterwards)
