### ISSUE TITLE
More feature file problems

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#660]
OK, I downloaded all of our pre-set transcription / feature combinations, and then tried to run them with the example corpus transcribed in each system, and ran into quite a lot of issues.

The example corpora using different systems can be found here: https://www.dropbox.com/sh/iogd1us0e6zuk8d/AAAwUYC8LknRxsr_M2T2612Oa?dl=0

1. It would be helpful if feature systems and corpora were listed alphabetically (or chronologically) -- currently there's no logic to the order as far as I can tell. -- @mdfry fixed this 

2. For many of the combinations, PCT crashed entirely when I got to the stage of loading the corpus. But, on re-opening PCT, the corpus was indeed listed and opened just find. 

The error message on crashing wasn't always entirely consistent, but was always a variation on the following:

![image](https://user-images.githubusercontent.com/7317450/36278461-bf9ed6c2-1248-11e8-99eb-ff68ea301b66.png)

The "KeyError" line was different depending on the feature system, though:

ipa2hayes -- KeyError 'Alveolar'
buckeye2hayes -- KeyError 'Column1'
buckeye2spe -- KeyError 'Alveopalatal'
celex2hayes -- KeyError 'Column1'
celex2spe -- KeyError 'Alveopalatal'
arpabet2spe -- KeyError 'Alveopalatal'
disc2spe  -- KeyError 'Column1'
sampa2spe -- KeyError 'Alveopalatal'

3. Whether or not the corpus-loading step caused PCT to crash, some of the corpora did not load with 'correct' features, similar to the problems we had before with the sampa2hayes system where things like [n] and [s] are [+syllabic] (or [+voc] in the SPE system).The following combinations had errors in terms of feature associations:
buckeye2hayes
buckeye2spe
celex2spe
arpabet2spe
cpa2hayes
cpa2spe
disc2hayes
disc2spe
klatt2hayes
klatt2spe
sampa2spe

4. Sometimes, when trying to View/Edit the feature system after it had been loaded, that action would cause PCT to crash. The following error would occur:
![image](https://user-images.githubusercontent.com/7317450/36278877-02e992b8-124a-11e8-800b-58fbfd558ed2.png)

This happened with:
celex2spe
cpa2spe
sampa2spe

5. Some of the feature systems are missing obvious sounds:
celex2hayes -- missing [e], [o], [u]
celex2spe -- missing [A], [i], [u]
cpa2hayes -- missing [e], [o]
cpa2spe -- missing [A], [i]
dis2hayes -- missing [e], [o]
sampa2spe -- missing [A], [i], [u]

**Comment by kchall** [comment]
@jsmackie 

OK, the feature systems have all been updated, and I think that solves issues (3) and (5) above, but (2) and (4) are still there, i.e., when loading certain corpora / transcription combinations, the program crashes with a key error. E.g., when I loaded the example corpus with Celex transcriptions, and the celex2spe feature system, the error is:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 289, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 449, in loadCorpus
    self.inventoryModel = None if specifier_check is None else self.generateInventoryModel()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 464, in generateInventoryModel
    inventoryModel = InventoryModel(self.corpusModel.corpus.inventory, copy_mode=False)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 934, in __init__
    self.sortData()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1402, in sortData
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 1402, in <lambda>
    sorted_cons_col_headers = sorted(list(self.consColumns), key=lambda x: self.cons_column_data[x][0])
KeyError: 'Alveopalatal'
Abort trap: 6

Other errors:
cmu2hayes: KeyError: 'Alveolar'
cpa2hayes: KeyError: 'Alveolar'
cpa2spe: KeyError: 'Alveopalatal'
disc2spe: KeyError: 'Alveopalatal'
...

(As above, when PCT is re-opened, the corpus is there and seems to be fine. It's just that it crashes the first time you try to load the corpus after it has been created.)


Wait a sec. I think it's when I specifically create a corpus using an SPE system after doing so with a Hayes one, or vice versa. E.g., if the system has crashed, and I go in and create a corpus with disc2spe, everything is fine, and then if I create a corpus with disc2hayes, it crashes with the Key Error 'Alveolar.' But then, if I re-open PCT and create a corpus with disc2hayes, everything is fine, and then if I create a corpus with disc2spe, it crashes with the Key Error 'Alveopalatal.'

So it's something to do with switching between systems? (And it happens even though the corpora have different names.)

***********
It's also still the case that looking at the View / edit feature system window sometimes causes a crash: 

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 315, in do_check
    function(self)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/main.py", line 605, in showFeatureSystem
    dialog = EditFeatureMatrixDialog(self, self.corpusModel.corpus, self.settings)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 507, in __init__
    self.changeDisplay()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/featuregui.py", line 612, in changeDisplay
    self.table.setModel(FeatureSystemTableModel(self.specifier))
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 873, in __init__
    self.generateData()
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 885, in generateData
    self.rows.append([x]+[self.specifier[x,y] for y in self.specifier.features])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/models.py", line 885, in <listcomp>
    self.rows.append([x]+[self.specifier[x,y] for y in self.specifier.features])
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 886, in __getitem__
    return self.matrix[item[0]][item[1]]
KeyError: 'EXTRA'
Abort trap: 6

e.g. this happens with celex2spe -- but not ipa2spe, even though they have the same feature set



*******
At any rate, the link to the Dropbox folder with the new .txt files is:
https://www.dropbox.com/sh/myaesxqrt2cp86b/AAAlTAvspeTkvH9qvVoxf-W8a?dl=0

And for the new .feature files:
https://www.dropbox.com/sh/r6zqadasptqeq15/AADtn0Ke5mg-ixfcwlgMsssMa?dl=0

**Comment by mdfry** [comment]
Should be solved - the problem happened because of a case mismatch in the strings used as keys. How the system works, if a segment did not exist in a feature inventory, it was generated with default 'n' value for all features and features were instantiated using lowercase strings. This is a mismatch with the strings in the actual feature files so a keyerror was raised.
