### ISSUE TITLE
Phonological Search bug

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#671]
When trying to populate the phonological search environments, PCT crashes with the following error:

2018-07-26 14:51:15.119 Python[37964:7517180] -[NSBox highlight:]: unrecognized selector sent to instance 0x12972a8c0
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

2018-07-26 14:51:15.138 Python[37964:7517180] WARNING: The same NSModalSession was stopped twice. The app may be mixing endSheet:returnCode: with NSModalSession APIs. This is likely to break in the future.
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QWidget::repaint: Recursive repaint detected
QBackingStore::endPaint() called with active painter on backingstore paint device
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter on backingstore paint device
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
2018-07-26 14:51:34.216 Python[37964:7517180] -[NSBox highlight:]: unrecognized selector sent to instance 0x12972a8c0
2018-07-26 14:51:34.220 Python[37964:7517180] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSBox highlight:]: unrecognized selector sent to instance 0x12972a8c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010010e32b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000100de2c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001001a6e04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000100084870 ___forwarding___ + 1456
	4   CoreFoundation                      0x0000000100084238 _CF_forwarding_prep_0 + 120
	5   libqmacstyle.dylib                  0x0000000124bd643f qt_plugin_instance + 27743
	6   libqmacstyle.dylib                  0x0000000124be010a qt_plugin_instance + 67882
	7   QtWidgets                           0x000000011135b2dc _ZN11QProxyStyle11qt_metacallEN11QMetaObject4CallEiPPv + 88044
	8   QtWidgets                           0x000000011132ebff _ZNK12QCommonStyle11drawControlEN6QStyle14ControlElementEPK12QStyleOptionP8QPainterPK7QWidget + 1007
	9   QtWidgets                           0x0000000111357661 _ZN11QProxyStyle11qt_metacallEN11QMetaObject4CallEiPPv + 72561
	10  QtWidgets                           0x000000011144af75 _ZN11QPushButton10paintEventEP11QPaintEvent + 117
	11  QtWidgets.so                        0x0000000110e642d8 _ZN14sipQPushButton10paintEventEP11QPaintEvent + 120
	12  QtWidgets                           0x00000001112eb841 _ZN7QWidget5eventEP6QEvent + 945
	13  QtWidgets                           0x00000001113ab221 _ZN15QAbstractButton5eventEP6QEvent + 145
	14  QtWidgets.so                        0x0000000110e65190 _ZN14sipQPushButton5eventEP6QEvent + 192
	15  QtWidgets                           0x00000001112b1752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 306
	16  QtWidgets                           0x00000001112b2a6f _ZN12QApplication6notifyEP7QObjectP6QEvent + 383
	17  QtWidgets.so                        0x0000000110e8180a _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	18  QtCore                              0x00000001056e4f7f _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 159
	19  QtWidgets                           0x00000001112e4229 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 2953
	20  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	21  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	22  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	23  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	24  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	25  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	26  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	27  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	28  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	29  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	30  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	31  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	32  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	33  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	34  QtWidgets                           0x00000001112e496c _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1100
	35  QtWidgets                           0x00000001112e43d3 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3379
	36  QtWidgets                           0x00000001112be7c7 _ZN14QWidgetPrivate10scrollRectERK5QRectii + 7431
	37  QtWidgets                           0x00000001112eba3b _ZN7QWidget5eventEP6QEvent + 1451
	38  QtWidgets.so                        0x0000000110e704f0 _ZN10sipQDialog5eventEP6QEvent + 192
	39  QtWidgets                           0x00000001112b1752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 306
	40  QtWidgets                           0x00000001112b2a6f _ZN12QApplication6notifyEP7QObjectP6QEvent + 383
	41  QtWidgets.so                        0x0000000110e8180a _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	42  QtCore                              0x00000001056e4f7f _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 159
	43  QtWidgets                           0x00000001112ba8cf _ZN12QApplication11qt_metacallEN11QMetaObject4CallEiPPv + 8335
	44  QtWidgets                           0x00000001112bb49f _ZN12QApplication11qt_metacallEN11QMetaObject4CallEiPPv + 11359
	45  QtWidgets                           0x00000001112ef33f _ZN7QWidget7repaintEiiii + 319
	46  QtWidgets                           0x00000001113ab592 _ZN15QAbstractButton15mousePressEventEP11QMouseEvent + 322
	47  QtWidgets.so                        0x0000000110e64908 _ZN14sipQPushButton15mousePressEventEP11QMouseEvent + 120
	48  QtWidgets                           0x00000001112eb668 _ZN7QWidget5eventEP6QEvent + 472
	49  QtWidgets                           0x00000001113ab221 _ZN15QAbstractButton5eventEP6QEvent + 145
	50  QtWidgets.so                        0x0000000110e65190 _ZN14sipQPushButton5eventEP6QEvent + 192
	51  QtWidgets                           0x00000001112b1752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 306
	52  QtWidgets                           0x00000001112b44ed _ZN12QApplication6notifyEP7QObjectP6QEvent + 7165
	53  QtWidgets.so                        0x0000000110e8180a _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	54  QtCore                              0x00000001056e4f7f _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 159
	55  QtWidgets                           0x00000001112b2080 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb + 896
	56  QtWidgets                           0x000000011130b761 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 9617
	57  QtWidgets                           0x000000011130a430 _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 4704
	58  QtWidgets                           0x00000001112b1752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 306
	59  QtWidgets                           0x00000001112b2a6f _ZN12QApplication6notifyEP7QObjectP6QEvent + 383
	60  QtWidgets.so                        0x0000000110e8180a _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	61  QtCore                              0x00000001056e4f7f _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 159
	62  QtGui                               0x0000000105004e1c _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE + 2956
	63  QtGui                               0x0000000104febefb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 155
	64  libqcocoa.dylib                     0x0000000121baa5b1 qt_plugin_instance + 143089
	65  CoreFoundation                      0x00000001000a6a61 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	66  CoreFoundation                      0x000000010016047c __CFRunLoopDoSource0 + 108
	67  CoreFoundation                      0x00000001000894c0 __CFRunLoopDoSources0 + 208
	68  CoreFoundation                      0x000000010008893d __CFRunLoopRun + 1293
	69  CoreFoundation                      0x00000001000881a3 CFRunLoopRunSpecific + 483
	70  HIToolbox                           0x000000010f0e9d96 RunCurrentEventLoopInMode + 286
	71  HIToolbox                           0x000000010f0e9a0f ReceiveNextEventCommon + 366
	72  HIToolbox                           0x000000010f0e9884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	73  AppKit                              0x0000000105be3a73 _DPSNextEvent + 2085
	74  AppKit                              0x0000000106379e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	75  AppKit                              0x0000000105e15e7b -[NSApplication _doModalLoop:peek:] + 476
	76  AppKit                              0x0000000105ffbb8a __33-[NSApplication runModalSession:]_block_invoke_2 + 69
	77  AppKit                              0x0000000105ffbb32 __33-[NSApplication runModalSession:]_block_invoke + 83
	78  AppKit                              0x00000001064a9219 _NSTryRunModal + 100
	79  AppKit                              0x0000000105ffba23 -[NSApplication runModalSession:] + 133
	80  libqcocoa.dylib                     0x0000000121ba92a6 qt_plugin_instance + 138214
	81  QtCore                              0x00000001056e0a72 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 418
	82  QtCore                              0x00000001056e5692 _ZN16QCoreApplication4execEv + 402
	83  QtWidgets.so                        0x0000000110f708c2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
	84  Python                              0x00000001007be4c8 _PyCFunction_FastCallDict + 552
	85  Python                              0x0000000100847e94 call_function + 612
	86  Python                              0x00000001008498a4 _PyEval_EvalFrameDefault + 5604
	87  Python                              0x0000000100847230 _PyEval_EvalCodeWithName + 2720
	88  Python                              0x00000001008473d4 PyEval_EvalCode + 100
	89  Python                              0x0000000100883f7e PyRun_FileExFlags + 206
	90  Python                              0x000000010088421f PyRun_SimpleFileExFlags + 447
	91  Python                              0x000000010089d86a Py_Main + 3914
	92  Python                              0x0000000100000dfe Python + 3582
	93  Python                              0x0000000100000c34 Python + 3124
	94  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by YuHsiangLo** [comment]
The latest version of PyQt5 (5.11.2) has [bugs](https://bugs.launchpad.net/rapid/+bug/1784236) that cause import error. The workaround is to downgrade to 5.9.2.
