### ISSUE TITLE
String similarity crashes when nonword is entered as Word 1.

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#674]
Error occurs when a nonword entered as Word 1. (for all algorithms)

The error message is as follows:

> Traceback (most recent call last):
>   File "c:\Users\Stanley\CorpusTools\corpustools\gui\windows.py", line 255, in newTable
>     self.calc()
>   File "c:\Users\Stanley\CorpusTools\corpustools\gui\windows.py", line 241, in calc
>     kwargs = self.generateKwargs()
>   File "c:\Users\Stanley\CorpusTools\corpustools\gui\ssgui.py", line 403, in generateKwargs
>     kwargs['query'] = (wordOne,wordTwo)
> UnboundLocalError: local variable 'wordOne' referenced before assignment

**Comment by YuHsiangLo** [comment]
@stannam I think I fixed the error. Could you try again and let me know if the problem still persists? Thanks!

**Comment by stannam** [comment]
@YuHsiangLo I think you fixed the problem! I tested every combination of algorithms and all worked perfectly. Thanks.
