### ISSUE TITLE
Functional load crashes when specifying environment

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#675]
Error occurs when limiting environment with the setting of the algorithm to change in entropy.

> Traceback (most recent call last):
>   File "c:\Users\Stanley\CorpusTools\corpustools\gui\flgui.py", line 57, in run
>     res = func(c, in_list, **kwargs)
>   File "c:\Users\Stanley\CorpusTools\corpustools\funcload\functional_load.py", line 283, in deltah_fl
>     environment_filter.lhs,
> AttributeError: 'list' object has no attribute 'lhs'

I tried it on the command line (with the following command) and the error seems to persist.
command: pct_funcload lemurian.corpus -p m -e -a deltah -w #

Error message:

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\Scripts\pct_funcload-script.py", line 11, in <module>
>     load_entry_point('corpustools==1.3.0', 'console_scripts', 'pct_funcload')()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\corpustools-1.3.0-py3.6.egg\corpustools\command_line\pct_funcload.py", line 130, in main
>     results = relative_deltah_fl(corpus, segpairs_or_segment, environment_filters=environment_filters, prevent_normalization=args.prevent_normalization)
> TypeError: relative_deltah_fl() got an unexpected keyword argument 'environment_filters'

**Comment by YuHsiangLo** [comment]
Note to myself:

- The problem in deltah_fl is more or less fixed, but I still need to go through other FL algorithms.
- There may be a mistake in how post-merger entropy is calculated.
- How do we determine whether to merger two words or not when environments are specified? All relevant segments in the words, or only the relevant segments in specified positions?
- What is the logical behind multiple environment filters? AND or OR?
