### ISSUE TITLE
CSJ inventory not generated

### ISSUE THREAD

**Issue by mdfry** [PhonologicalCorpusTools/CorpusTools#683]
CSJ loaded with csj2hayes has features correctly noted for segments, but the inventory window does not incorporate features (i.e. everything is uncategorized)

**Comment by mdfry** [comment]
The issue is that our csj2hayes feature file doesn't have 'labiodental,' 'trill' and 'lateral' columns, but in PCT those columns are required for a system to be minimally considered a 'hayes' system.

**Comment by kchall** [comment]
Can confirm that adding those features into csj2hayes allows for auto-categorization, and the documentation does list the required features for making this happen, for both Hayes and SPE. 

https://github.com/PhonologicalCorpusTools/CorpusTools/blob/master/docs/source/transcriptions_and_feature_systems.rst
