### ISSUE TITLE
IPhOD corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#690]
Check to see why homographs are missing from our version of the IPhOD corpus (and update if needed).

**Comment by kchall** [comment]
Update -- make the IPHOD corpus download have options -- can either download without homographs (the default before 2019) or with homographs included (though this may double-count frequencies for homographs)

**Comment by stannam** [comment]
Sorry, but we need to make sure 'iphod_with_homographs' is identical to the original IPhOD (https://www.iphod.com/).

While I was testing the neighbourhood density function (#770), I noticed that the neighbour lists for 'cat' from the iPhoD homepage ([link](https://www.iphod.com/calculator/runcalc_v2_0.php?pseudo=not&wordtrans=K.AE.T&shneigh=on&nphon=true&ph=true)) and PCT (calculating on 'iphod_with_homographs') are not identical. 

There are a couple of words missing in the PCT's results. See the attached excel file. The cells in red are missing words.
[comparison.xlsx](https://github.com/PhonologicalCorpusTools/CorpusTools/files/7208207/comparison.xlsx)

**Comment by stannam** [comment]
I created iphod_with_homographs.corpus from scratch again. 

Hopefully, this never happens again, but to make life easier when it does happen, the raw wordlist as the .txt format is added to the dropbox folder (...\CORPUS\raw txt files\iphod_without_homographs.txt). Next time, create a corpus from that file.
