### ISSUE TITLE
Pronunciation variants through spelling

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#703]
If you try to create an ILG corpus and tell PCT to allow the transcriptions to vary within lexical item, but there’s only ONE transcription line, it will create the corpus but then crash on trying to load it. i.e., it can’t link varying transcriptions through the spellings, which one might otherwise expect. Either we should allow it to do so, or we should have it warn users explicitly that this cannot be done.

**Comment by kchall** [comment]
Hmm, I tried this with a new ILG corpus for verification, and got the following error:

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 91, in run
    corpus = load_discourse_ilg(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 246, in load_discourse_ilg
    data = ilg_to_data(corpus_name, path, annotation_types,stop_check, call_back)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/text_ilg.py", line 192, in ilg_to_data
    tier_elements[0].begin = level_count
AttributeError: 'str' object has no attribute 'begin'

The corpus is the one called "pron_var_from_spelling.txt" and is also attached.

[pron_var_from_spelling.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/3683463/pron_var_from_spelling.txt)

**Comment by stannam** [comment]
I noticed that in pron_var_from_spelling.txt, the transcription is not delimited whereas in ilg_sample.txt (previous ilg sample) each phoneme is separated by '.' . I am working on it :)

**Comment by stannam** [comment]
close?

**Comment by stannam** [comment]
note: currently (Nov 2021), the default transcription is not allowed to vary on an ilg with two lines (spelling and ONE transcription). see #787

**Comment by kchall** [comment]
^ Elaborating on the above: pronunciation variants are NOT ALLOWED to be linked through spelling. See the "diff_spelling_one_can_variants" tab in the "interlinear variants.xlsx" file in the Dropbox folder. 

This has been listed explicitly in https://github.com/PhonologicalCorpusTools/CorpusTools/blob/master/docs/source/pronunciation_variants.rst.
