### ISSUE TITLE
Acoustic Similarity

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#718]
Trying to calculate acoustic similarity using amplitude envelopes causes PCT to crash entirely, with the following error:

Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 1344
    out = out_full[ind]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/_arraytools.py", line 45
    b = a[a_slice]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

**Comment by stannam** [comment]
It seems the distance values are actually calculated as below. Could simply be a GUI issue when reporting these results....
![image](https://user-images.githubusercontent.com/43150234/72945338-67f42700-3d30-11ea-8526-346d415a487f.png)

**Comment by stannam** [comment]
solved?

**Comment by stannam** [comment]
crashes, when the user gives 0 as the number of coefficients with MFCC is selected.
