### ISSUE TITLE
creating new corpus -- column name issue?

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#719]
I just tried to create a new corpus with column names "Word", "Trans", and "Freq." The "Frequency" column just got treated as an arbitrary numeric column, and PCT added a new frequency column filled with "1" values. It works fine if the column name is literally "Frequency." Didn't we fix this before such that the column name is more flexible?

**Comment by stannam** [comment]
I could replicate this issue when I running from the code and on released versions (tested on 1.4.1, 1.4.0 and 1.3.0; same results -- a new frequency column created). :(

**Comment by stannam** [comment]
lexicon.py.orig:991 seems like an earlier solution to the problem. Basically, all kinds of expected variation of 'frequency' were hard-coded, and if the user input matches one then regard it as 'frequency.'  

['abs_freq', 'freq_per_mil', 'sfreq', 'lowercase_freq', 'log10_freq', 'freq', 'frequency'] are the list of acceptable column names for frequency. I think the list contains all reasonable 'variations.' I will try to recycle this solution.

**Comment by stannam** [comment]
- add 'frequency' to the list of Annotation type.
