### ISSUE TITLE
mutual information -- algorithm question

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#730]
In the documentation for MI (https://corpustools.readthedocs.io/en/latest/mutual_information.html), we state that both "word-internal" pointwise mutual information (which is symmetric) and "ordered pair" pointwise mutual information (which is not symmetric) are implemented in PCT. However, in the dialogue box, there's no option for selecting which version to use, and only one MI value is returned in the results, with no indication of which one it is!

My guess is that it's currently doing ordered pair MI, because it won't calculate the values for the pairs if they're listed in the other direction, but it would be good if someone could (a) verify that this is correct and then (b) either give people the option to actually do either one or (c) clarify that only ordered-pair is available, and label it as such in the results.

**Comment by stannam** [comment]
Seems pointwise mutual information to me. (Not symmetric)

Corpus | PCT version | First sg | Second sg | Domain | Halved edges | Tier | Frequency type | Variants? | Min word freq. | MI value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
example | 1.4.1 | ɡ | ɑ | Unigram/Bigram | Yes | Transcription | Type | Canonical Form | 0 | 2.816
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
example | 1.4.1 | ɑ | ɡ | Unigram/Bigram | Yes | Transcription | Type | Canonical Form | 0 | 1.816

**Comment by stannam** [comment]
Currently, only the ordered pair-wise mutual information is implemented in PCT. I updated the documentation accordingly.
( cf. commit 1f79c5dc8e6659f68f1269df39897284c4992a74 )

**Comment by kchall** [comment]
Ha ha, I may have just solved this mystery...note that there's an option for "set domain to word" and in the documentation, it also says: "Domain: Choosing “set domain to word” will change the calculation so that the calculation is for word-internal co-occurrence pMI. In this case, the order and adjacency of the bigram does not matter; it is simply treated as a pair of segments that could occur anywhere in a word." 

So this *should* do the other calculation! Stanley, can you confirm that it does indeed do this, and then update the documentation again to make this clearer (if neither of us noticed this when we were actively looking, it clearly isn't obvious!). Thanks!

**Comment by stannam** [comment]
YES! I confirmed that selecting the checkbox calculates word-internal co-occurrence pMI.

Below is the subset of the example corpus. I'm going to calculate unordered pMI for two segments [s] and [i]. (s, i) in this ordering, does not exist as a bigram so only word-internal co-occurrence pMI can be calculated. Ordered pMI cannot be calculated.

Seq. | Spelling | Transcription | Frequency 
-- | -- | -- | -- 
1 | shashi | ʃ.ɑ.ʃ.i | 43.0
2 | shi | ʃ.i | 2.0
3 | shisata | ʃ.i.s.ɑ.t.ɑ | 3.0
4 | shushoma | ʃ.u.ʃ.o.m.ɑ | 126.0
5 |tishenishu | t.i.ʃ.e.n.i.ʃ.u | 96.0

<img src="https://user-images.githubusercontent.com/43150234/81649845-cd564b80-93e5-11ea-8c6b-9903ac5633c3.png" height="60">


Prob. of word with both [s] and [i] → 1 (Word 3) out of 5, therefore, 1/5 = 0.2

Prob. of word with [s] → 4 (Words 1, 2, 3, and 5) out of 5, therefore, 4/5 = 0.8
Prob. of word with [i] → 1 (Word 3) out of 5, therefore, 1/5 = 0.2

<img src="https://user-images.githubusercontent.com/43150234/81650047-21613000-93e6-11ea-97d7-421d76d160da.png" height="50">

In PCT:
![image](https://user-images.githubusercontent.com/43150234/81650177-566d8280-93e6-11ea-8231-98b8ab1e4a9f.png)


and the result is 0.322; Same as the hand calculation.
![image](https://user-images.githubusercontent.com/43150234/81650334-992f5a80-93e6-11ea-83f3-dde7f14ef8ce.png)


I'll revert the recent changes I made on the documentation, and state more explicitly that 'word-internal co-occurrence MI (non-directional)' can be calculated by selecting the 'Set domain to word' checkbox.

**Comment by stannam** [comment]
close?
