### ISSUE TITLE
Mutual Information -- environment filter / selection

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#735]
Add the environment selection option to the mutual information algorithm. E.g. if someone wants to calculate MI only in word-initial position, etc.

**Comment by stannam** [comment]
cf. predictability of distribution

**Comment by stannam** [comment]
close?

**Comment by stannam** [comment]
need to write documentation.

**Comment by stannam** [comment]
Environment filter implemented. Word-boundary issues solved. Also, the documentation is updated to reflect those changes. 
(cf. commits 597f68cb47a2fb61c99690a1128e098f61aa0f10 82b9a28f88e68c886786beeb9e57e31992064ef3 and c569db7f113458f60b58b9988b32907755c6d36c )
