### ISSUE TITLE
Results dialogue boxes

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#736]
Go through all the algorithms and add an "analysis name" column that lists the analysis (e.g. "functional load," "mutual information," "transitional probability,") etc. as a separate entry in each row. Then the "Result" column should always be called "Result" in all the algorithms.

**Comment by stannam** [comment]
related:
- The title of the results dialogue for 'informativity' should be changed (currently, set as 'Mutual information results').
- In 'Acoustic similarity,' the column 'Is similarity' with the value of 'Yes/No' can be misleading.
- The 'result' column should be uniformly at the rightmost side (not the case for 'Informativity,' 'Kullback-Leibler,' and 'Acoustic similarity').
-- Suggested order of columns: 'Corpus', 'PCT ver.', 'Analysis name', analysis particular parameters, ..., and 'Result'

Q: For 'Kullbaqck Leibler,' multiple columns are needed for the results. (Kullback-Leibler divergence, Possible UR, and Spurious allophones)
