### ISSUE TITLE
Feature system issues

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#748]
1. [h] is under uncategorized (as mentioned in issue #584)
2. In SPE, [ɹ] is a mid front vowel.
![image](https://user-images.githubusercontent.com/43150234/93386777-121f4280-f81d-11ea-8924-c6c8f1360917.png)

3. compared to the list of SPE features in Mielke (2008), a number of features are missing in ipa2spe.feature. 
4. due to 3., [m] and [m̩] (syllabic m) are identical in features. (c.f., other syllabic consonants are not specified in the feature file)

**Comment by stannam** [comment]
**consonantal**	
**syllabic**	
covered	
delayed release of secondary closure

**Comment by kchall** [comment]
Hmm, [consonantal] should definitely be in there, as it's part of the 'original' set of features in chapter 7. It's defined on p. 302 as "Consonantal sounds are produced with a radical obstruction in the midsagittal region of the vocal tract; nonconsonantal sounds are produced without such an obstruction." Here's a table of their original major class features: 

![image](https://user-images.githubusercontent.com/7317450/94480297-f146dd80-018a-11eb-94c7-f490bf4dd20b.png)

They do suggest in chapter 8 (p. 354) that [vocalic] should be replaced with [syllabic], as in the following table, to specifically handle syllabic consonants:

![image](https://user-images.githubusercontent.com/7317450/94480529-45ea5880-018b-11eb-93d9-d81dd641d2a9.png)

I think I'm inclined to simply have BOTH [vocalic] and [syllabic] in there, since PCT is much more about descriptive features than it is about analytical features. 

Will this take care of all the above issues? What about [h]?

**Comment by stannam** [comment]
[h] will still be uncategorized, unless we add another column for 'glottal'.

Note: SPE classifies [h] as a glide, not fricative.

**Comment by kchall** [comment]
If you mean a column in the actual consonant inventory chart, that's fine, and yes, fine to put it in as a glide, as that's what SPE does (as with glottal stop). I don't want to add a [glottal] feature though. The place features for [h] (p. 307) are: [-ant, -cor, -high, +low, -back].

**Comment by stannam** [comment]
- Add columns for [consonantal] and [syllabic] in whatever2spe.feature files.

**Comment by stannam** [comment]
* [h] and [ɹ] should end up uncategorized in the current categorization.
    - [h] is [-consonantal], thus should NOT be one of the consonants.
    - [ɹ] is tricky. Currently, our SPE rows (manners) are stop, nasal, fricative, and lateral. I am not sure where to place [ɹ]. 
        - It seems the SPE book regards both [l] and [ɹ] as 'liquids' so my thought is to replace the lateral row with liquids.
* There are some discrepancies between our feature system and the SPE book: In the book, [l] is [+vocalic], [ɹ] is [+lat], unlike our system.

**Comment by kchall** [comment]
@stannam can you find a page reference for [ɹ] being [+lat]?

**Comment by stannam** [comment]
@kchall Oooops.. Sorry, I think I was not fully awake then. I meant [+continuant], and when I checked now both [l] and [ɹ] are [+cont]! The book even mentioned that '[l] [...] must be distinguished from [r] by the feature of "laterality."' (p. 318, Ch. 7)
![image](https://user-images.githubusercontent.com/43150234/96512145-e70d8180-1214-11eb-9ee2-3fb2af4699d8.png)

**Comment by stannam** [comment]
- In SPE, [l] should be [ **+** vocalic].
- For both hayes and SPE systems: add a row for 'Approximant.' (cf. the standard IPA consonant chart.)
    - in SPE, change 'lateral' into 'lateral approximant' 
    - SPE doesn't seem to assume the [approximant] feature: not in the list on page 299. 
- In SPE, [h] should be excluded from vowels. Two solutions:
    - The default features for vowels should be [-consonantal, **+voice**] (the solution discussed during the meeting today), or
    - [h] should be unspecified of [low] [high] and [back], following the Hayes system. (cf. Currently [h] is [-back, -high, +low])
        - When I quickly checked the book (Section 4.2 in Chapter 7), [h] was not considered (see the table below) in terms of those features. I believe there should be reasons that we initially gave those values in PCT, so I'll look into other parts of the SPE book and Mielke (2008). 
![image](https://user-images.githubusercontent.com/43150234/96521813-f269a880-1226-11eb-93d4-b03f33a4a6d1.png)
(from p. 305)

**Comment by stannam** [comment]
cf. Phonological_CorpusTools_Public/other/example_corpus_in_different_transcription_systems.xlsx

**Comment by stannam** [comment]
* Minor changes to the existing features/transcriptions 
    * Hayes
        * Make sure [ɹ] is [+consonantal] in other transcription-to-hayes files than ipa2hayes.
        * Match the inventory chart to Table 4.7 in Hayes (2008: 95)
    * SPE
        * Change a row name in the SPE inventory chart: approximant  --> liquid

* Create master feature files for the SPE and Hayes systems, respectively. 
    - A master feature file has each transcription as a column, as well as the feature columns, and PCT should refer to each transcription column.
    - Need to create the master feature, change the way PCT downloads and processes feature files. (No longer need to download individual 'transcription2feature' once the user downloads the super-feature.
