### ISSUE TITLE
can't load corpus with column labelled "spelling" used as transcription

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#756]
If a user has a corpus with a column labelled "spelling," but tells PCT to use it as transcription (and there's no other transcription column), the following error occurs. Note that simply calling the column by a different name (whether that's 'transcription' or something else) does solve the problem.

Traceback (most recent call last):
  File "/Users/KCH/Desktop/CorpusTools/corpustools/gui/iogui.py", line 101, in run
    corpus = load_corpus_csv(**self.kwargs)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/io/csv.py", line 252, in load_corpus_csv
    corpus.add_word(word, allow_duplicates=True)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 3139, in add_word
    added_default = self.update_inventory(word.transcription)
  File "/Users/KCH/Desktop/CorpusTools/corpustools/corpus/classes/lexicon.py", line 3189, in update_inventory
    if transcription.stress_pattern:
AttributeError: 'str' object has no attribute 'stress_pattern'

**Comment by kchall** [comment]
[no_names.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/6183945/no_names.txt)
[no_spelling.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/6183946/no_spelling.txt)
[no_transcrip.txt](https://github.com/PhonologicalCorpusTools/CorpusTools/files/6183947/no_transcrip.txt)

**Comment by kchall** [comment]
^ sample files to test

**Comment by YuHsiangLo** [comment]
Commit 0bb064f69e66d62218e5cf9a75c18448d2e5f9c5 should fix this.

**Comment by YuHsiangLo** [comment]
Commit 789f5970ef20507ff52524fb36f0a284992c2fe1 should have addressed this.

**Comment by kchall** [comment]
Hmm, this still seems to be a problem for me. If I load the 'no_transcription' corpus and force PCT to use the column labelled 'spelling' as transcription, I get the same error as in the initial report.

**Comment by YuHsiangLo** [comment]
Commit 789009a9865c9b2952b2a375d2f00fad96b279d1 addresses the issue
