### ISSUE TITLE
SPE features causing crash

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#757]
Maybe cf. #748 ?

Currently, if you change the example corpus to ipa2spe (instead of the default ipa2hayes), *all* segments are uncategorized. Then, going to manage feature systems and trying to update the categorization causes PCT to crash, but there's no error message.

**Comment by stannam** [comment]
Changing the feature moves all segments to 'uncategorized'. But 'Autocategorize' works properly on my machine. ('Update default feature' does nothing apparently, but still it does not crash PCT.) I tested this on both old and new ipa2spe.feature files. 

Could this be another OS-dependent issue? 😥

**Comment by kchall** [comment]
It's working properly on my Mac, too...I don't know why it didn't work two hours ago.... Weird!
