### ISSUE TITLE
[BUG] Duplicated search too strict

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#762]
**Describe the bug**
When a search is duplicated, it's good that repeated results don't get added to the results window. But the current set-up seems slightly too strict, in that super-set searches are also not allowed. See below for details.

**Sample corpus file**
The example corpus.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'phonological search.'
2. Search for [a] preceded by [m]. 
3. Reopen dialog box and remove the target [a]. Replace with [+syllabic].
4. Add results to current results window.
5. PCT gives warning and doesn't re-calculate.

**Expected behaviour**
I expected a new summary line to be added that has the sum of all the [m+Vowel] words listed (including any overlap with previous lines -- i.e., the results line should look like it does if you do the [m+Vowel] search without any preceding search). The individual results shouldn't have the repeated results, but should add in the other new results (like [tatomi]).

**Operating system and PCT version**
 - OS: macOS 10.13.6
 - PCT version: current master, 28 June 2021

**Comment by stannam** [comment]
memo to myself
- duplicate_check(self) in views.py should be more lenient.
- also for the switch between individual and summary results, PCT should know the mapping between a token and search type.
- Does this also applies to other analysis functions? (cf currently mutual information, transitional prob, etc also block 'duplicated' searches)

**Comment by kchall** [comment]
This is all fixed and the documentation updated. Thank you!
