### ISSUE TITLE
[BUG] Syllable search crashes PCT

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#763]
**Describe the bug**
When searching for a syllable [ma], PCT crashes

**Sample corpus file**
The syllabified example corpus.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Phonological search'
2. Create a syllable. Onset exactly matches [m], nucleus exactly matches [a].
3. Start new results window.
4. PCT crashes.

**Expected behaviour**
Results for the syllable search.

**Operating system and PCT version**
 - OS: macOS 10.13.6
 - PCT version: current master, 28 June 2021

**Comment by stannam** [comment]
It is strange that this error does not occur on my machine. 

I have searched for the [ma] syllable (both segments set as 'exactly matches')
 
![image](https://user-images.githubusercontent.com/43150234/123714561-6b47e800-d82b-11eb-8fd0-b45600fb7f30.png)

.. and without specifying environments.

So the parameters look like the below.
![image](https://user-images.githubusercontent.com/43150234/123714615-887cb680-d82b-11eb-9338-5478cb0d3abc.png)


Interestingly, my search does not crash PCT and shows results as follows

![image](https://user-images.githubusercontent.com/43150234/123714677-a4805800-d82b-11eb-83c3-4b045344a72a.png)

![image](https://user-images.githubusercontent.com/43150234/123714689-a9dda280-d82b-11eb-85de-4a1452fffbaf.png)

**Comment by kchall** [comment]
Hmm, this was apparently a fluke on my end due to not syncing fully (?). Seems to be working for everyone (including me) now.
