### ISSUE TITLE
Representation of syllable structure in results

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#771]
The basic principles for representing syllable structure in results windows are great. But, there's a weird quirk when two separate syllable-based environments are selected (e.g. in phonological search).

In segment-based environments, the desired behaviour is observed, and each environment is listed separately in the summary results:

Specified environments ([#ma] and [ni#]):

![image](https://user-images.githubusercontent.com/7317450/130681750-54dda30a-a5da-4932-a7eb-6bd9b1c9d0e7.png)

ALMOST Correct summary results window (each environment listed separately):

![image](https://user-images.githubusercontent.com/7317450/130681875-68cfd541-4bd6-49ea-afa2-16fe3f27a1f3.png)

** Actually, there's an error here, too! While the results are listed on separate lines, their frequencies are incorrectly summed together. The type and token counts for [#ma] should be 2 and 7, respectively, and those for [ni#] should be 1 and 33. 

But in syllable-based environments, the environments are concatenated, and the results again added together:

Specified environments ([#ma] and [ni#]):

![image](https://user-images.githubusercontent.com/7317450/130681241-47b62f96-fb85-4963-b710-c8aeb35a8bf6.png)

Incorrect summary results window (environments concatenated together and frequencies again summed):

![image](https://user-images.githubusercontent.com/7317450/130681380-64328a27-5745-4124-8947-c29a3f1540bf.png)

Note that the actual search still seems to be correct, in that the individual results are looking for ONE environment or the other, not both simultaneously:

![image](https://user-images.githubusercontent.com/7317450/130681492-8c36133a-96cd-4c2a-915e-6eaf50b1a1ef.png)

**Comment by stannam** [comment]
**1. The summed up frequencies in the summary window (for both segment and syllable searches)**
    - This bug is now fixed. the frequencies are summed up separately by the environment
    - Question: what if one of the environments does not have results? Do we still want to have a row with 0 frequencies in the summary window? Currently, the environment with no result does not show up.
    - The error resulted from the mistake I made when we changed the 'concept' of summarized results. 
    - Previously, it was simply a summary of individual results, then we switched to present 'search parameters.' For example, when doing a search with #_{+consonantal} (find words that starts with a consonant), the previous summary window presented many rows, each with a consonant and the number of words that start with that consonant. However, that is not the way we want PCT to work, so we currently have only one row in the summary window.
    - However, the problem is that a search with multiple environments are still one search, so when I changed the codes I made PCT to summarize too far and summing up all the frequencies into one token and one type freq. -- and these are the numbers that inserted to many environments.

**Segment search (envs: [#ma] and [ni#])** (and the summary result window)

![image](https://user-images.githubusercontent.com/43150234/130737133-4881dd46-475a-4ab3-9212-1dbe6dd6db96.png)


**2. Concatenated environments (only syllable search)**
    - This bug was an easy fix -- I didn't tried a search with multiple environments and I didn't notice this error. :(

**Syllable search (envs: [#ma] and [ni#])** (and the summary result window)
![image](https://user-images.githubusercontent.com/43150234/130737417-52ef6463-827a-4543-8d15-fda890fb1ba2.png)

**Comment by kchall** [comment]
Everything above seems to be fixed -- thanks!
