### ISSUE TITLE
[BUG] Default trascription variants and interlinear gloss

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#787]
Typically, a corpus with variant forms involves three attributes: orthography, default transcription, and alternative transcription. Alternative transcription varies within lexical items. 

We also allow variant forms without the alternative transcription attribute. I.e., the user can select canonical transcriptions to vary within lexical items (see #703). The problem in this case is that analysis functions cannot recognize transcription.

Two options

**1. No canonical but only variants**

- When Transcription (default) varies within lexical items, and Transcription (alternative) is not provided,
  - In all analysis functions, the 'pronunciation variants' option should allow the variant options, but not 'use canonical forms.'
![image](https://user-images.githubusercontent.com/43150234/138025831-6f43c98d-78a5-4f80-8371-ef4e3c60778c.png)
  - Issues
    - On the main corpus table, which transcription should be presented? (currently, whatever appears first is shown)
    - 'List pronunciation variants' not working.
    - How should 'Edit word' work? Which variant should this edit?

**2. Do not allow default transcription to vary**
- Then a corpus must have a non-varying canonical column..

**Comment by stannam** [comment]
update: 

**1. Pronunciation variants is only allowed for 'transcription (alternative)'  (solved - commits not pushed yet)**

**We chose path 2.** In other words, transcription (default) does NOT vary. Following this, commit ff5a7c06e2f7a478c5a239de7a78ef7eb5f4a45e blocks the user from selecting '...vary within lexical items' for anything other than transcription (alternative).

Now, a two-lined interlinear corpus cannot handle pronunciation variants. If a ilg file has two lines, there should be one line for spelling and another for canonical transcription. If the transcription varies, they should be treated as if homographs.

e.g., in the following mini example, two 'tomato's should be different entries
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Stanley/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Stanley/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



tomato | tomato | tomato
-- | -- | --
təmeɪɾoʊ | təmeɪɾoʊ | təmatoʊ



</body>

</html>



Whereas in the example below, one 'tomato' has pronunciation variants (with 'canonical' being [təmeɪɾoʊ]).
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Stanley/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Stanley/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



tomato | tomato | tomato
-- | -- | --
təmeɪɾoʊ | təmeɪɾoʊ | təmeɪɾoʊ
təmeɪɾoʊ | təmeɪɾoʊ | təmatoʊ



</body>

</html>


Also, see 'example_files/variants/interlinear_variants' (in the shared dropbox storage).


**2. Two-lined interlinear has no inventory categorization (not solved)**

Autocategorize does not work when a two-lined interlinear file is imported. All segments are under 'uncategorized segments'

**Comment by kchall** [comment]
Can confirm that all three cases in the Excel file are working for me.

**Comment by kchall** [comment]
I think this is all working, and the documentation is up to date.
