### ISSUE TITLE
[BUG] Unwanted mergers

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#791]
**Describe the bug**
After loading a corpus, the user cannot edit an existing word to have the same spelling and transcription as an existing word. PCT only adds up the frequency to the existing word. 

**Sample corpus file**
'Example' corpus

**To Reproduce**
1. Load 'Example'
2. Right click on 'nata' and then edit the word as shown below -- same transcription and spelling as 'mata.'

![image](https://user-images.githubusercontent.com/43150234/144363509-b41e3a3b-9b39-41cc-a5f1-92d8b548bdd3.png)

3. See error

**Expected behavior**
Ask the user before doing anything.

![image](https://user-images.githubusercontent.com/43150234/144363694-e0f4c97a-4829-4756-be57-fbc79c36af00.png)

**Additional context**
(... should have noticed when working on #717 😂)

**Comment by stannam** [comment]
Problem: once 'separate entry' then 
- they cannot be merged later. :( 
- confusing when adding a new word and selecting 'add frequency' (i.e., where to add freq?) -- currently, freq added to the first of the duplicates.

solution (long run): 
- always add / edit as separate entry
- add new function 'merge words' with more than one words selected.

**Comment by stannam** [comment]
close?

**Comment by kchall** [comment]
Maybe we should just change the warning message to specify that if frequency is added, it is added to the first entry if there are duplicates? And also add an explicit 'cancel' button? Thus:

Your input 'xx' already exists in the corpus.
You can add it as a separate entry,
or simply add frequency to the existing entry.
If there are multiple instances of 'xx' already in the corpus, 
the frequency will be added to the first such entry.
[Add as a separate entry] [Add frequency to existing word] [Cancel]

**Comment by stannam** [comment]
Tested on 'example' corpus. 
'ta' already exists so creating 'ta' [tɑ] prompts the message as left. Editing 'mata' to be identical to 'nata' (in both spelling and transcription) prompts the message as right.
All three buttons work as intended :)
![image](https://user-images.githubusercontent.com/43150234/149039504-f245a11a-6288-457e-bdea-30d640ff0dec.png)

**Comment by kchall** [comment]
Looks good, thanks!
