### ISSUE TITLE
[BUG] Tab key not working correctly in feature autocomplete

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#804]
**Describe the bug**
The tab key does not select the highlighted feature among the candidates.

**Sample corpus file**
Example

**To Reproduce**
1. Go to Select features (e.g., in phonological search)
2. Enter 'back'
3. Use arrow key to highlight '+back'
4. Press the tab key to select
5. See '0back' selected instead of '+back'

**Expected behavior**
The highlighted feature should be automatically entered to the field.

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/43150234/164155477-5b882f81-1714-4b7c-be78-692deea5da6d.gif)

**Operating system and PCT version**
 - OS: win10
 - PCT version: v1.5

**Additional context**
The enter key works.

**Comment by stannam** [comment]
confirmed working on my Mac virtual machine

**Comment by kchall** [comment]
(also confirmed to work on my Mac -- OS 11.3.1)
